INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '959a81da-ce46-4c0a-b0b7-77f0900c8bdc',
                'DRIVER_AVAILABLE',
                'active',
                28.559771138412188,
                -81.3786187848897,
                'Orlando',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'long_haul',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 1}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                88,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'f1d7c209-44b2-4364-b440-204d51e40ea9',
                'DRIVER_AVAILABLE',
                'active',
                28.561823095695537,
                -81.42670416339692,
                'Orlando',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'local',
                '{"direction": "local", "truck_type": "20T", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                84,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '75b141b8-c998-4c5d-8ba3-14948feaeef8',
                'DRIVER_AVAILABLE',
                'active',
                40.45801106546274,
                -80.03381646527083,
                'Pittsburgh',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'north',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                78,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '22300789-2e70-45b7-b53d-dd007648af7a',
                'DRIVER_AVAILABLE',
                'active',
                40.45480633089833,
                -80.01662596050083,
                'Pittsburgh',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'long_haul',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 45}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6e2d849b-9c81-4784-979b-6d38f074bdde',
                'DRIVER_AVAILABLE',
                'active',
                40.422191213856266,
                -80.02305657947586,
                'Pittsburgh',
                'United States',
                'Phoenix',
                'United States',
                33.4484,
                -112.074,
                'north',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                15,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '21122bdf-6b6e-459a-9325-1439f02996af',
                'DRIVER_AVAILABLE',
                'active',
                40.467902072523636,
                -79.99854058282871,
                'Pittsburgh',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'south',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ec1fee5c-6f81-4438-aee7-482a2b8cfc48',
                'DRIVER_AVAILABLE',
                'active',
                40.48879057887374,
                -79.99512144361175,
                'Pittsburgh',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'long_haul',
                '{"direction": "east", "truck_type": "20T", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '9c31c3af-1de0-4295-9110-c7c0fffe35f1',
                'DRIVER_AVAILABLE',
                'active',
                40.408835300470365,
                -80.00557850365308,
                'Pittsburgh',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'north',
                '{"direction": "west", "truck_type": "20T", "available_hours": 33}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e8727582-cb90-4500-b986-ed1cae004ad8',
                'DRIVER_AVAILABLE',
                'active',
                40.48325206388148,
                -79.98874649702886,
                'Pittsburgh',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'long_haul',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '2307d887-f09c-41a1-a18f-538e6454065f',
                'DRIVER_AVAILABLE',
                'active',
                40.41559063167258,
                -80.00844267802263,
                'Pittsburgh',
                'United States',
                'Houston',
                'United States',
                29.7604,
                -95.3698,
                'south',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'fb11b8a3-d46d-4a66-b404-4266e034afd7',
                'DRIVER_AVAILABLE',
                'active',
                39.94959007828746,
                -75.16458039206628,
                'Philadelphia',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'north',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '484a4545-94f9-403e-bd55-cbafa681d4b5',
                'DRIVER_AVAILABLE',
                'active',
                39.93435743901617,
                -75.14999503841895,
                'Philadelphia',
                'United States',
                'Stockton',
                'United States',
                37.9577,
                -121.2908,
                'local',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                88,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'd7ffb041-c32e-495d-971d-90f6c99e3117',
                'DRIVER_AVAILABLE',
                'active',
                39.97726982602678,
                -75.15565102105752,
                'Philadelphia',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'north',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 27}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                26,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '324ce80c-289c-431e-8c2a-26369f3b63fd',
                'DRIVER_AVAILABLE',
                'active',
                39.91501748213135,
                -75.15972452648252,
                'Philadelphia',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'local',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                85,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '04e2b473-4148-457d-98ae-7c6a82628c2b',
                'DRIVER_AVAILABLE',
                'active',
                39.97137207069489,
                -75.2066767386773,
                'Philadelphia',
                'United States',
                'Miami',
                'United States',
                25.7617,
                -80.1918,
                'south',
                '{"direction": "north", "truck_type": "Van", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                99,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'bb70e322-0d41-479e-a3de-b75d417f2536',
                'DRIVER_AVAILABLE',
                'active',
                39.90893901953273,
                -75.20575323070028,
                'Philadelphia',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 51}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                19,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ba00eb13-e48c-414b-bb77-264c4a7f4bbf',
                'DRIVER_AVAILABLE',
                'active',
                39.96549917695557,
                -75.14546029441554,
                'Philadelphia',
                'United States',
                'Fort Worth',
                'United States',
                32.7555,
                -97.3308,
                'north',
                '{"direction": "local", "truck_type": "Van", "available_hours": 60}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '373e31b9-62b0-4c0e-a9f7-307ef41968d3',
                'DRIVER_AVAILABLE',
                'active',
                39.91998163440152,
                -75.19055095882307,
                'Philadelphia',
                'United States',
                'Albuquerque',
                'United States',
                35.0844,
                -106.6504,
                'south',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 3}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                88,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0a1fbfde-7ca9-456a-9274-394d7f68b373',
                'DRIVER_AVAILABLE',
                'active',
                39.967504776398435,
                -75.18846124518075,
                'Philadelphia',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '631baf3d-089d-411b-ad47-f1e1773b37b8',
                'DRIVER_AVAILABLE',
                'active',
                39.92623017712208,
                -75.13701977497469,
                'Philadelphia',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'south',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 47}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                82,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '8fde9a5f-b830-401b-a465-f02e40d93f59',
                'DRIVER_AVAILABLE',
                'active',
                40.702713235024056,
                -74.01614525852061,
                'New York',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'local',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 60}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'aee50594-9e33-40ac-893b-1d1cb3e688d2',
                'DRIVER_AVAILABLE',
                'active',
                40.72779779751637,
                -73.97793608917421,
                'New York',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 16}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                81,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '9a79f8ba-1486-416a-9c27-fe34709d253f',
                'DRIVER_AVAILABLE',
                'active',
                40.703009924546045,
                -74.00160672045126,
                'New York',
                'United States',
                'Fort Worth',
                'United States',
                32.7555,
                -97.3308,
                'north',
                '{"direction": "local", "truck_type": "20T", "available_hours": 30}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                76,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'db3d50a0-ddc9-412a-bbec-0d7c9421d5e6',
                'DRIVER_AVAILABLE',
                'active',
                40.680725301342356,
                -74.02027481666349,
                'New York',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'local',
                '{"direction": "north", "truck_type": "20T", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '3bf5b8fd-9fca-47be-b14f-ad4e74e3c9c6',
                'DRIVER_AVAILABLE',
                'active',
                40.705172294985225,
                -74.00283092298105,
                'New York',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'local',
                '{"direction": "north", "truck_type": "20T", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '78060890-8896-4a2f-84dc-aa59a603aa69',
                'DRIVER_AVAILABLE',
                'active',
                40.762232415713854,
                -74.04143298817858,
                'New York',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'north',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                4,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e5467126-4add-4124-afb5-5f4bafbc6117',
                'DRIVER_AVAILABLE',
                'active',
                40.722896543823076,
                -74.04615587662522,
                'New York',
                'United States',
                'Dallas',
                'United States',
                32.7767,
                -96.797,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 2}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'bf7d6671-e19d-4687-8781-a41d9710e00f',
                'DRIVER_AVAILABLE',
                'active',
                40.750223691461656,
                -73.97330287117455,
                'New York',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'local',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                7,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '3cce0011-2a49-4e2b-b077-ab19b3c7158d',
                'DRIVER_AVAILABLE',
                'active',
                42.409535374475624,
                -71.0556729696467,
                'Boston',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 18}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '96baaac6-6c34-427d-b47f-5464297ed10a',
                'DRIVER_AVAILABLE',
                'active',
                42.38102930012739,
                -71.00926099737832,
                'Boston',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'long_haul',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 35}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                12,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'd4852809-cba2-40e4-9349-e79d1c5b7197',
                'DRIVER_AVAILABLE',
                'active',
                42.40794437803896,
                -71.03768415237359,
                'Boston',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'north',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 6}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                1,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '5843ae39-8b4b-483d-a73b-fd4e4eea6910',
                'DRIVER_AVAILABLE',
                'active',
                42.37870501012832,
                -71.03714805037148,
                'Boston',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'north',
                '{"direction": "local", "truck_type": "20T", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                86,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a9366acb-037d-4446-87fb-757ec5698fa8',
                'DRIVER_AVAILABLE',
                'active',
                42.32733029200601,
                -71.10883412241087,
                'Boston',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'local',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                21,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '09ec31ac-5081-4d1c-afb4-96a27d38da28',
                'DRIVER_AVAILABLE',
                'active',
                42.34537320923199,
                -71.03787941312618,
                'Boston',
                'United States',
                'Cincinnati',
                'United States',
                39.1031,
                -84.512,
                'local',
                '{"direction": "south", "truck_type": "20T", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                80,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6fd23f6d-b89d-43dd-8777-2c00acc34ad3',
                'DRIVER_AVAILABLE',
                'active',
                42.33395219150402,
                -71.05545079107962,
                'Boston',
                'United States',
                'Cincinnati',
                'United States',
                39.1031,
                -84.512,
                'south',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 30}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                5,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '69bda3f8-2fe5-4ec1-9748-b35278248c62',
                'DRIVER_AVAILABLE',
                'active',
                42.38265575822369,
                -71.03673168137135,
                'Boston',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'north',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                66,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'c9df1c26-7ea7-4a96-8923-7314ce991ebb',
                'DRIVER_AVAILABLE',
                'active',
                39.294119733323285,
                -76.58529931525055,
                'Baltimore',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'local',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'b044ef2a-3b30-4ca8-aeda-a549427cd59c',
                'DRIVER_AVAILABLE',
                'active',
                39.327829059517875,
                -76.61498189615355,
                'Baltimore',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'local',
                '{"direction": "east", "truck_type": "20T", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                2,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'b047fc47-4096-4e28-8089-f85f125bf6ad',
                'DRIVER_AVAILABLE',
                'active',
                39.2943253388527,
                -76.59285134139137,
                'Baltimore',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'south',
                '{"direction": "south", "truck_type": "20T", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                4,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'aa066eb8-fe4d-477c-9267-7e8cf91b35a8',
                'DRIVER_AVAILABLE',
                'active',
                39.29963614210284,
                -76.65073448365582,
                'Baltimore',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'south',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                5,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'f1be9b8e-2039-49b7-b347-67ef356a69d6',
                'DRIVER_AVAILABLE',
                'active',
                39.26289059711362,
                -76.60766395849582,
                'Baltimore',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'north',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                38,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '618b9425-ddc3-4954-a24a-e460f480933b',
                'DRIVER_AVAILABLE',
                'active',
                38.93081679276234,
                -77.05750639611361,
                'Washington',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'local',
                '{"direction": "south", "truck_type": "20T", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '5ec9db06-33a5-40c5-9e17-be6e533436ee',
                'DRIVER_AVAILABLE',
                'active',
                38.94742393652508,
                -77.07314886146865,
                'Washington',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 28}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ee6b4c6f-5a0e-4b69-91c1-68878c09097e',
                'DRIVER_AVAILABLE',
                'active',
                38.86897497290612,
                -77.04362482711967,
                'Washington',
                'United States',
                'Austin',
                'United States',
                30.2672,
                -97.7431,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '3c9f06fe-5622-497f-b483-182c457b9ae3',
                'DRIVER_AVAILABLE',
                'active',
                38.943643300626505,
                -77.00853742040567,
                'Washington',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'south',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'b5a7695e-66ad-4cd2-8458-83bc258021cf',
                'DRIVER_AVAILABLE',
                'active',
                38.894967898562925,
                -77.08504785157261,
                'Washington',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 5}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'c1d83e52-0595-4575-9dc9-a55cf853618e',
                'DRIVER_AVAILABLE',
                'active',
                38.86263067720221,
                -77.05283747938309,
                'Washington',
                'United States',
                'Des Moines',
                'United States',
                41.5868,
                -93.625,
                'long_haul',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e8a1427f-340b-4990-bb1a-8b07ea19641c',
                'DRIVER_AVAILABLE',
                'active',
                38.90882465397869,
                -77.04576813618503,
                'Washington',
                'United States',
                'Stockton',
                'United States',
                37.9577,
                -121.2908,
                'long_haul',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 55}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '05dbcf56-346f-40e7-8f5f-f5b7ef0f0586',
                'DRIVER_AVAILABLE',
                'active',
                38.943627368556506,
                -77.01218791001222,
                'Washington',
                'United States',
                'Jacksonville',
                'United States',
                30.3322,
                -81.6557,
                'long_haul',
                '{"direction": "south", "truck_type": "Van", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                26,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'bfefc988-b57b-404c-b539-0bdbb8cc2aa0',
                'DRIVER_AVAILABLE',
                'active',
                38.907189947513544,
                -77.03990693766643,
                'Washington',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'long_haul',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                31,
                4
            );