INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '86e72b35-3b1b-4455-ae05-3ef5e0b62245',
                'DRIVER_AVAILABLE',
                'active',
                45.53585577992512,
                -122.68689291028336,
                'Portland',
                'United States',
                'Fresno',
                'United States',
                36.7378,
                -119.7871,
                'local',
                '{"direction": "local", "truck_type": "Van", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                95,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '2d04fb56-6b47-4fc9-b28d-e227579a2d30',
                'DRIVER_AVAILABLE',
                'active',
                45.47716965237712,
                -122.6942244947268,
                'Portland',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'south',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 41}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                20,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'b232b973-52f4-4a17-8da0-261300b48ea3',
                'DRIVER_AVAILABLE',
                'active',
                45.553177599806524,
                -122.72474100964985,
                'Portland',
                'United States',
                'Omaha',
                'United States',
                41.2565,
                -95.9345,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 15}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                21,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '735e7747-7e54-44bd-b80f-50f8496f49a5',
                'DRIVER_AVAILABLE',
                'active',
                45.49927641886801,
                -122.65080507728727,
                'Portland',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'local',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                17,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '906a8779-bd7c-4adb-9b20-912e12eefef9',
                'DRIVER_AVAILABLE',
                'active',
                45.51328494313484,
                -122.69087996814855,
                'Portland',
                'United States',
                'Phoenix',
                'United States',
                33.4484,
                -112.074,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                75,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '655fbd17-43bf-4ebf-bbf6-59e2f2af9b7d',
                'DRIVER_AVAILABLE',
                'active',
                45.55211319868964,
                -122.64185853362498,
                'Portland',
                'United States',
                'Cincinnati',
                'United States',
                39.1031,
                -84.512,
                'north',
                '{"direction": "north", "truck_type": "20T", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                59,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '62d6e19c-0455-401d-ae54-89c6ae8eefc5',
                'DRIVER_AVAILABLE',
                'active',
                45.55205226679525,
                -122.72258801217552,
                'Portland',
                'United States',
                'Cincinnati',
                'United States',
                39.1031,
                -84.512,
                'local',
                '{"direction": "west", "truck_type": "20T", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'd2e17292-feb6-40eb-99ed-928269e0188b',
                'DRIVER_AVAILABLE',
                'active',
                45.48076783451611,
                -122.71283685409942,
                'Portland',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'local',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 53}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                87,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '7147d92f-c2f9-4314-ba36-a1cff23657a9',
                'DRIVER_AVAILABLE',
                'active',
                39.73530444428738,
                -104.98649456827741,
                'Denver',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'south',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                20,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'cc48f23c-0440-4068-afa2-95e4f5be5c09',
                'DRIVER_AVAILABLE',
                'active',
                39.76545385323697,
                -104.98925369080538,
                'Denver',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                6,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e8a12493-a0b7-4deb-8016-25dfe4a0da55',
                'DRIVER_AVAILABLE',
                'active',
                39.70467038559359,
                -104.9562481196206,
                'Denver',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'local',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '989dee1e-d5ca-4a20-a2a9-fc0a26bb8eae',
                'DRIVER_AVAILABLE',
                'active',
                39.74641586484167,
                -105.03313822186882,
                'Denver',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'north',
                '{"direction": "south", "truck_type": "20T", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '7f68de7e-d051-4bb2-95a6-94416379337f',
                'DRIVER_AVAILABLE',
                'active',
                39.69177589403374,
                -105.0147852393166,
                'Denver',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 14}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                75,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6c8cd568-9b05-465d-bbbe-2dbed3478891',
                'DRIVER_AVAILABLE',
                'active',
                39.707940844791885,
                -104.94148487086558,
                'Denver',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                55,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '412447e7-07a9-4432-b9de-9588a493860f',
                'DRIVER_AVAILABLE',
                'active',
                39.70203303894035,
                -105.00930890960076,
                'Denver',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'local',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 53}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ecb8b81b-0222-4031-ad6b-2b7b873e2c36',
                'DRIVER_AVAILABLE',
                'active',
                39.72500041409737,
                -104.9706746890041,
                'Denver',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                4,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '8f9f62a5-b255-413b-b976-b3e1f3837481',
                'DRIVER_AVAILABLE',
                'active',
                35.0456897019425,
                -106.68745969069658,
                'Albuquerque',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 60}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                73,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '7dc2bd4d-9ae1-4129-afe5-6914bc491786',
                'DRIVER_AVAILABLE',
                'active',
                35.08581157991899,
                -106.64991871983923,
                'Albuquerque',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                81,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'fa4b6006-2d46-4ccb-b9f0-a31f6450220a',
                'DRIVER_AVAILABLE',
                'active',
                35.04017088844139,
                -106.68312803149375,
                'Albuquerque',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'long_haul',
                '{"direction": "west", "truck_type": "Van", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                6,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '494ae31e-b1b2-416b-8546-44493902b340',
                'DRIVER_AVAILABLE',
                'active',
                35.050050122771246,
                -106.61332987839408,
                'Albuquerque',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'south',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                76,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'c132344f-6b59-4cb6-8dc5-68f0d4a453a7',
                'DRIVER_AVAILABLE',
                'active',
                35.03709096015062,
                -106.62722770152702,
                'Albuquerque',
                'United States',
                'Salt Lake City',
                'United States',
                40.7608,
                -111.891,
                'local',
                '{"direction": "west", "truck_type": "20T", "available_hours": 28}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                78,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '59efd10d-1473-4ce3-a415-809125c77ccc',
                'DRIVER_AVAILABLE',
                'active',
                35.05449352296761,
                -106.65021014489469,
                'Albuquerque',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'local',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 47}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '3aa3fc4d-96a0-48d9-a6e4-132b8ccd0d0f',
                'DRIVER_AVAILABLE',
                'active',
                35.12053589973351,
                -106.60142370720897,
                'Albuquerque',
                'United States',
                'St. Louis',
                'United States',
                38.627,
                -90.1994,
                'local',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 53}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                60,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '178a4361-00dc-4533-9836-9007a3ce0f39',
                'DRIVER_AVAILABLE',
                'active',
                35.09856682039483,
                -106.69272672620927,
                'Albuquerque',
                'United States',
                'Phoenix',
                'United States',
                33.4484,
                -112.074,
                'local',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                62,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '2948fada-6902-4f15-b317-d31eb11ffdee',
                'DRIVER_AVAILABLE',
                'active',
                31.736544154284314,
                -106.47457174288643,
                'El Paso',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'south',
                '{"direction": "east", "truck_type": "Van", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                2,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '275809c5-43c8-4e3f-a976-b35f23ae675e',
                'DRIVER_AVAILABLE',
                'active',
                31.733133293424395,
                -106.43624908485536,
                'El Paso',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'local',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'fd30b9a3-dab2-4076-9795-4d3fe9335b11',
                'DRIVER_AVAILABLE',
                'active',
                31.769953888695838,
                -106.52176737559475,
                'El Paso',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                74,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'd8b5117a-c5a6-44ab-b38f-00f82f3ee56b',
                'DRIVER_AVAILABLE',
                'active',
                31.726587546611974,
                -106.49699520135364,
                'El Paso',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'long_haul',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                68,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ffd9af36-5bc7-4934-aece-183c34290c25',
                'DRIVER_AVAILABLE',
                'active',
                31.714827191642044,
                -106.44341354426011,
                'El Paso',
                'United States',
                'Detroit',
                'United States',
                42.3314,
                -83.0458,
                'north',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 18}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                96,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '94ef5323-029c-47c3-8fd6-959e2902e476',
                'DRIVER_AVAILABLE',
                'active',
                31.7504618595745,
                -106.44279155725752,
                'El Paso',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'north',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 27}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                64,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'fdd27a69-b338-46b2-acbe-c0410eada1cf',
                'DRIVER_AVAILABLE',
                'active',
                31.75043752202872,
                -106.45669183212578,
                'El Paso',
                'United States',
                'Stockton',
                'United States',
                37.9577,
                -121.2908,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '5fec168c-0de4-4200-bfdd-0dbe831f6e3d',
                'DRIVER_AVAILABLE',
                'active',
                31.714177419512488,
                -106.49614734980983,
                'El Paso',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'local',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 1}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '468ad0b2-596a-45d0-9f10-65d361fd9c01',
                'DRIVER_AVAILABLE',
                'active',
                32.73058762861043,
                -96.83276848064416,
                'Dallas',
                'United States',
                'Albuquerque',
                'United States',
                35.0844,
                -106.6504,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                94,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e3d50f48-9f55-40cf-abd4-fd0a61607152',
                'DRIVER_AVAILABLE',
                'active',
                32.74035062160835,
                -96.82838567238335,
                'Dallas',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'local',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                87,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '7fe5c961-56ff-4d8b-ab87-e12cde96be8a',
                'DRIVER_AVAILABLE',
                'active',
                32.77585938611332,
                -96.7745055997399,
                'Dallas',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'local',
                '{"direction": "local", "truck_type": "20T", "available_hours": 47}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '19794ceb-8b2b-4b46-a39e-f0e2d0f44b85',
                'DRIVER_AVAILABLE',
                'active',
                32.78127314283498,
                -96.81785476312076,
                'Dallas',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 38}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                40,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'cc4b98e8-a525-42a2-8cd9-1f662cef6fb1',
                'DRIVER_AVAILABLE',
                'active',
                32.7918344172014,
                -96.78539103888434,
                'Dallas',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'long_haul',
                '{"direction": "south", "truck_type": "20T", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                8,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'bd3c4790-2ee1-471c-a05a-9540e2f8f518',
                'DRIVER_AVAILABLE',
                'active',
                32.75262791654344,
                -96.76795900177557,
                'Dallas',
                'United States',
                'Seattle',
                'United States',
                47.6062,
                -122.3321,
                'north',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                96,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6cf3a51b-4744-4e1c-b603-0c1af2101e55',
                'DRIVER_AVAILABLE',
                'active',
                32.78730405251379,
                -96.78230467720697,
                'Dallas',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'south',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e0bdda92-a587-4133-9170-f530afdd25a1',
                'DRIVER_AVAILABLE',
                'active',
                32.744116973433876,
                -97.32736343568783,
                'Fort Worth',
                'United States',
                'Detroit',
                'United States',
                42.3314,
                -83.0458,
                'local',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 15}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'c413d611-039c-408c-a987-202d0deb7675',
                'DRIVER_AVAILABLE',
                'active',
                32.71832736838828,
                -97.37960899388023,
                'Fort Worth',
                'United States',
                'Seattle',
                'United States',
                47.6062,
                -122.3321,
                'south',
                '{"direction": "north", "truck_type": "Van", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                40,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '2a46fe4c-91fc-454c-95d2-7ca84de31032',
                'DRIVER_AVAILABLE',
                'active',
                32.78303306798968,
                -97.31739186948765,
                'Fort Worth',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'south',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '2b07a001-0b26-4b96-95f3-deb798e968c0',
                'DRIVER_AVAILABLE',
                'active',
                32.75568734092328,
                -97.29554356489064,
                'Fort Worth',
                'United States',
                'Minneapolis',
                'United States',
                44.9778,
                -93.265,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                48,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a2e5d708-7aa7-453a-bdac-ff35c6c5a292',
                'DRIVER_AVAILABLE',
                'active',
                32.80414055154909,
                -97.34979925049741,
                'Fort Worth',
                'United States',
                'Des Moines',
                'United States',
                41.5868,
                -93.625,
                'long_haul',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '8590a4dd-28b7-4d33-b145-4fd4051f0ada',
                'DRIVER_AVAILABLE',
                'active',
                32.728751136436394,
                -97.32948389729164,
                'Fort Worth',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'local',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4b787e02-f610-4c41-8272-262c8fc2829a',
                'DRIVER_AVAILABLE',
                'active',
                32.739589136348094,
                -97.37486163978379,
                'Fort Worth',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'south',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                79,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '18d9748f-ca9f-448b-8d14-72f4b49baab9',
                'DRIVER_AVAILABLE',
                'active',
                29.775400742547127,
                -95.33335365972219,
                'Houston',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'north',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 39}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '3e208ada-9d9d-4d7b-bef1-f691e89c786e',
                'DRIVER_AVAILABLE',
                'active',
                29.715321696944866,
                -95.34409070750958,
                'Houston',
                'United States',
                'Oklahoma City',
                'United States',
                35.4676,
                -97.5164,
                'local',
                '{"direction": "local", "truck_type": "Van", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ff0d8a4c-4820-4fbe-804a-88c4a3858e1b',
                'DRIVER_AVAILABLE',
                'active',
                29.739967889828016,
                -95.39137218379747,
                'Houston',
                'United States',
                'Stockton',
                'United States',
                37.9577,
                -121.2908,
                'south',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 60}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                12,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a86098fd-7727-433a-958b-6daeec41caff',
                'DRIVER_AVAILABLE',
                'active',
                29.772913556044216,
                -95.4114173350847,
                'Houston',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'south',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                41,
                4
            );