INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                36.14349782006675,
                -115.15851437062408,
                'Las Vegas',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                1
            
            FROM auth.users WHERE email = 'lisa.thomas54@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                36.131597505141926,
                -115.11125329538822,
                'Las Vegas',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                4
            
            FROM auth.users WHERE email = 'david.johnson40@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                36.14210183916443,
                -115.17853782469345,
                'Las Vegas',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'local',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                73,
                2
            
            FROM auth.users WHERE email = 'tom.wilson97@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                36.1489275562226,
                -115.0925708732904,
                'Las Vegas',
                'United States',
                'Oklahoma City',
                'United States',
                35.4676,
                -97.5164,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 49}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                3
            
            FROM auth.users WHERE email = 'mike.smith75@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                36.21106793452963,
                -115.0957154116588,
                'Las Vegas',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                4
            
            FROM auth.users WHERE email = 'jessica.smith64@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                36.17831702420381,
                -115.14787770927676,
                'Las Vegas',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'north',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                13,
                2
            
            FROM auth.users WHERE email = 'emma.jackson75@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                36.199107041291036,
                -115.13370984422237,
                'Las Vegas',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'local',
                '{"direction": "south", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                60,
                3
            
            FROM auth.users WHERE email = 'john.brown47@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                36.12154264940415,
                -115.13243209361545,
                'Las Vegas',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'north',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                74,
                1
            
            FROM auth.users WHERE email = 'david.johnson58@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.421460228182994,
                -112.10230265439642,
                'Phoenix',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'south',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 56}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                5,
                2
            
            FROM auth.users WHERE email = 'jessica.jackson63@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.420286851551474,
                -112.10107012929316,
                'Phoenix',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'north',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                99,
                1
            
            FROM auth.users WHERE email = 'lisa.thomas12@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.45157361961028,
                -112.09831322268342,
                'Phoenix',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'long_haul',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                3
            
            FROM auth.users WHERE email = 'emma.smith73@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.43662536849271,
                -112.0374777000801,
                'Phoenix',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'south',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                0
            
            FROM auth.users WHERE email = 'john.jackson58@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.48190151756739,
                -112.07092923857282,
                'Phoenix',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'north',
                '{"direction": "north", "truck_type": "Van", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                41,
                1
            
            FROM auth.users WHERE email = 'jessica.brown68@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.242947393843345,
                -111.01881906659563,
                'Tucson',
                'United States',
                'Austin',
                'United States',
                30.2672,
                -97.7431,
                'north',
                '{"direction": "south", "truck_type": "20T", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                71,
                4
            
            FROM auth.users WHERE email = 'john.brown94@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.258353571132005,
                -110.9545716561542,
                'Tucson',
                'United States',
                'Albuquerque',
                'United States',
                35.0844,
                -106.6504,
                'south',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                56,
                5
            
            FROM auth.users WHERE email = 'sarah.jackson14@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.201807663082064,
                -110.98197217405122,
                'Tucson',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'local',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                66,
                3
            
            FROM auth.users WHERE email = 'lisa.smith86@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.23015944872616,
                -110.96227388087162,
                'Tucson',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                3
            
            FROM auth.users WHERE email = 'jessica.moore85@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.267112747490025,
                -110.92942475493224,
                'Tucson',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'north',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                46,
                3
            
            FROM auth.users WHERE email = 'sarah.taylor45@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                40.73177255898036,
                -111.89250332997133,
                'Salt Lake City',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'long_haul',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                4
            
            FROM auth.users WHERE email = 'robert.thomas50@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                40.73407821280936,
                -111.92367352743732,
                'Salt Lake City',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'north',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                57,
                1
            
            FROM auth.users WHERE email = 'jessica.smith37@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                40.8106547628651,
                -111.877362281577,
                'Salt Lake City',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'long_haul',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                34,
                4
            
            FROM auth.users WHERE email = 'jane.anderson97@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                40.754117121017366,
                -111.87602251167002,
                'Salt Lake City',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'south',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                97,
                0
            
            FROM auth.users WHERE email = 'jane.doe24@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                40.75539583720818,
                -111.91164445825586,
                'Salt Lake City',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                3
            
            FROM auth.users WHERE email = 'jessica.brown67@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                40.711165165980205,
                -111.8471890863279,
                'Salt Lake City',
                'United States',
                'Jacksonville',
                'United States',
                30.3322,
                -81.6557,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 3}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                1
            
            FROM auth.users WHERE email = 'sarah.thomas59@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                40.79012642358112,
                -111.91690346032566,
                'Salt Lake City',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'south',
                '{"direction": "south", "truck_type": "20T", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                22,
                0
            
            FROM auth.users WHERE email = 'john.thomas93@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                40.74932302732291,
                -111.89470477554052,
                'Salt Lake City',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'north',
                '{"direction": "west", "truck_type": "20T", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                30,
                2
            
            FROM auth.users WHERE email = 'john.brown76@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                40.743737841475124,
                -111.92183200988741,
                'Salt Lake City',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'long_haul',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                5
            
            FROM auth.users WHERE email = 'tom.johnson35@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.60237297138048,
                -116.16931066968934,
                'Boise',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 38}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                6,
                2
            
            FROM auth.users WHERE email = 'jessica.thomas71@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.58275183478121,
                -116.20974185647601,
                'Boise',
                'United States',
                'Seattle',
                'United States',
                47.6062,
                -122.3321,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 39}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                94,
                0
            
            FROM auth.users WHERE email = 'jessica.wilson93@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.659918526681814,
                -116.19855979350466,
                'Boise',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                19,
                2
            
            FROM auth.users WHERE email = 'sarah.jackson31@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.583626281196224,
                -116.21360440300664,
                'Boise',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                0
            
            FROM auth.users WHERE email = 'tom.moore72@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.59252317368653,
                -116.19717638761625,
                'Boise',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 49}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                2
            
            FROM auth.users WHERE email = 'emma.moore82@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.60854159499731,
                -116.24248425336869,
                'Boise',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'local',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 37}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                2
            
            FROM auth.users WHERE email = 'sarah.anderson52@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.617831835685415,
                -116.17603157352069,
                'Boise',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'north',
                '{"direction": "local", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                76,
                4
            
            FROM auth.users WHERE email = 'robert.wilson59@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.60025436799159,
                -116.16069910194526,
                'Boise',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                77,
                3
            
            FROM auth.users WHERE email = 'mike.moore40@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.610141016606306,
                -116.17951979914478,
                'Boise',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                88,
                2
            
            FROM auth.users WHERE email = 'jane.jackson11@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.641646854657346,
                -116.23474904996586,
                'Boise',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'south',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                5
            
            FROM auth.users WHERE email = 'tom.johnson42@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.58746275179726,
                -122.36880582229999,
                'Seattle',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                5
            
            FROM auth.users WHERE email = 'tom.moore10@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.62659329015634,
                -122.33513671261633,
                'Seattle',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'local',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 58}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                4
            
            FROM auth.users WHERE email = 'lisa.smith39@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.6108131108218,
                -122.37464834159451,
                'Seattle',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'local',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                74,
                3
            
            FROM auth.users WHERE email = 'lisa.taylor33@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.588183783283974,
                -122.36482371113298,
                'Seattle',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'long_haul',
                '{"direction": "local", "truck_type": "20T", "available_hours": 41}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                2
            
            FROM auth.users WHERE email = 'robert.taylor20@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.639617442905596,
                -122.35012230769973,
                'Seattle',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                5
            
            FROM auth.users WHERE email = 'robert.doe21@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.61385118737285,
                -122.34900958388764,
                'Seattle',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                69,
                3
            
            FROM auth.users WHERE email = 'jessica.smith35@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.250055542461666,
                -122.41829025967255,
                'Tacoma',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'north',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                1
            
            FROM auth.users WHERE email = 'robert.moore43@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.22592321994998,
                -122.41478047076119,
                'Tacoma',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'north',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 14}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                4
            
            FROM auth.users WHERE email = 'mike.moore91@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.228531599516195,
                -122.45719810828874,
                'Tacoma',
                'United States',
                'Cincinnati',
                'United States',
                39.1031,
                -84.512,
                'north',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                85,
                3
            
            FROM auth.users WHERE email = 'john.moore36@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.27953882556437,
                -122.44650709736604,
                'Tacoma',
                'United States',
                'Omaha',
                'United States',
                41.2565,
                -95.9345,
                'south',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                3
            
            FROM auth.users WHERE email = 'mike.brown91@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.24755315876866,
                -122.47530277387332,
                'Tacoma',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'south',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                3
            
            FROM auth.users WHERE email = 'sarah.doe39@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.27127027297047,
                -122.42269199178797,
                'Tacoma',
                'United States',
                'Dallas',
                'United States',
                32.7767,
                -96.797,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 2}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                0
            
            FROM auth.users WHERE email = 'robert.wilson55@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                47.253135785026544,
                -122.4550319035774,
                'Tacoma',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'long_haul',
                '{"direction": "local", "truck_type": "Van", "available_hours": 30}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                0
            
            FROM auth.users WHERE email = 'jessica.thomas30@example.com';
