INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '2590e03d-5871-482b-9603-db83a9963917',
                
                'DRIVER_AVAILABLE',
                'active',
                29.734792467247196,
                -95.35151684403633,
                'Houston',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'north',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                85,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '172db8ec-f79a-4b22-a483-d0038cc66e1e',
                
                'DRIVER_AVAILABLE',
                'active',
                29.777265139205625,
                -95.40575764335203,
                'Houston',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                45,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '43a31cda-f2dd-4a30-aebe-c50a0661fe18',
                
                'DRIVER_AVAILABLE',
                'active',
                29.74771099213569,
                -95.33883200496105,
                'Houston',
                'United States',
                'Seattle',
                'United States',
                47.6062,
                -122.3321,
                'south',
                '{"direction": "west", "truck_type": "20T", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '02c864ca-93ea-474e-b4a9-eab812a1307c',
                
                'DRIVER_AVAILABLE',
                'active',
                29.778743668834625,
                -95.34765608752414,
                'Houston',
                'United States',
                'Detroit',
                'United States',
                42.3314,
                -83.0458,
                'long_haul',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                43,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c4b6c24f-3f49-49f2-9d79-152fcc4f7656',
                
                'DRIVER_AVAILABLE',
                'active',
                29.429577486021117,
                -98.51228818188787,
                'San Antonio',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'local',
                '{"direction": "north", "truck_type": "Van", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                95,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ebc8d872-f31e-45d4-8031-b099af8920dc',
                
                'DRIVER_AVAILABLE',
                'active',
                29.436616801412463,
                -98.52192533193005,
                'San Antonio',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'north',
                '{"direction": "south", "truck_type": "20T", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                69,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '256fcebe-6c47-413b-8ceb-7cdcc2aedf61',
                
                'DRIVER_AVAILABLE',
                'active',
                29.40125645343186,
                -98.51119479090472,
                'San Antonio',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'south',
                '{"direction": "local", "truck_type": "Van", "available_hours": 57}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '75754f61-309a-4f01-b777-cb303664085d',
                
                'DRIVER_AVAILABLE',
                'active',
                29.38867652558365,
                -98.46304309731235,
                'San Antonio',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4715f785-3b5f-4b8f-b504-7d7a2227d1d8',
                
                'DRIVER_AVAILABLE',
                'active',
                29.47170507899308,
                -98.5167336057501,
                'San Antonio',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                17,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '46c7733c-7d25-4326-b63d-1deabf708de5',
                
                'DRIVER_AVAILABLE',
                'active',
                29.376307526927267,
                -98.47415429898429,
                'San Antonio',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '202711ab-85b8-422a-bb4d-36790c301743',
                
                'DRIVER_AVAILABLE',
                'active',
                30.301290887584518,
                -97.70110549603295,
                'Austin',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'local',
                '{"direction": "north", "truck_type": "20T", "available_hours": 9}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4337c714-0fb6-477a-97c2-bfdeae5a549d',
                
                'DRIVER_AVAILABLE',
                'active',
                30.24702051250972,
                -97.7765190167603,
                'Austin',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                79,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ef7e3591-dda3-4d0d-8745-bbb7a06ddd4d',
                
                'DRIVER_AVAILABLE',
                'active',
                30.248193247643407,
                -97.73717836768542,
                'Austin',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '29a3b269-c84b-4812-b7b3-9cb7ce5d0caf',
                
                'DRIVER_AVAILABLE',
                'active',
                30.246341257113276,
                -97.74793994470527,
                'Austin',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'local',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ee79fe6c-303f-45d4-8031-b099af8920dc',
                
                'DRIVER_AVAILABLE',
                'active',
                30.219615140658796,
                -97.77404160551278,
                'Austin',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'south',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                73,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '705868e7-e80c-4252-8861-05f0ad7e6700',
                
                'DRIVER_AVAILABLE',
                'active',
                30.315087655638436,
                -97.70717453156877,
                'Austin',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'north',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                98,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '31ff12f3-13a3-4ede-8504-42d91b353b85',
                
                'DRIVER_AVAILABLE',
                'active',
                27.53748123140756,
                -99.49998051400571,
                'Laredo',
                'United States',
                'Austin',
                'United States',
                30.2672,
                -97.7431,
                'north',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'a61b6112-bec7-4f2c-aa37-89e0a7773b6f',
                
                'DRIVER_AVAILABLE',
                'active',
                27.492404040446303,
                -99.52621907108112,
                'Laredo',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'local',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 58}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                79,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b62fe23e-cfe2-4af8-9b78-630d34e616ee',
                
                'DRIVER_AVAILABLE',
                'active',
                27.50078616524217,
                -99.51366303054797,
                'Laredo',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'north',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4f17f734-11c7-4b04-ad2a-71c8fee923c7',
                
                'DRIVER_AVAILABLE',
                'active',
                27.57764195648477,
                -99.49914394944315,
                'Laredo',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'north',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 1}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                79,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'a8d7b5c7-f5a0-473b-84fd-ff999227f4ee',
                
                'DRIVER_AVAILABLE',
                'active',
                27.51739156195533,
                -99.51744204849668,
                'Laredo',
                'United States',
                'San Antonio',
                'United States',
                29.4241,
                -98.4936,
                'local',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 2}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'f140ddf2-41bc-4aa4-9ae2-40dcca547702',
                
                'DRIVER_AVAILABLE',
                'active',
                27.57640213909522,
                -99.50678838961232,
                'Laredo',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'local',
                '{"direction": "west", "truck_type": "20T", "available_hours": 39}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                12,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9d086936-a422-4375-ad56-27a1904ced14',
                
                'DRIVER_AVAILABLE',
                'active',
                27.498463289580894,
                -99.49003280550629,
                'Laredo',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'local',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'fb006d0a-e07a-4187-978a-e163ff58dd97',
                
                'DRIVER_AVAILABLE',
                'active',
                27.499908147989448,
                -99.52007167831846,
                'Laredo',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'local',
                '{"direction": "local", "truck_type": "20T", "available_hours": 49}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                49,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '6b998f84-0259-49cb-8dbf-02751336cd5d',
                
                'DRIVER_AVAILABLE',
                'active',
                27.51682022484712,
                -99.49486489203761,
                'Laredo',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'local',
                '{"direction": "north", "truck_type": "20T", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                95,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '640d96eb-8b98-4223-8aa6-64b9b0f281a2',
                
                'DRIVER_AVAILABLE',
                'active',
                27.54106229482474,
                -99.43438940903457,
                'Laredo',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'd5a4b99b-4312-4ed8-8029-35335d9a848c',
                
                'DRIVER_AVAILABLE',
                'active',
                35.46874538132681,
                -97.5440450127037,
                'Oklahoma City',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '57c9dd89-47d2-4ceb-be05-95d8dc7cb82e',
                
                'DRIVER_AVAILABLE',
                'active',
                35.47979901619702,
                -97.5605768111425,
                'Oklahoma City',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'long_haul',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 9}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ffbb00ca-21d5-4c44-8c3f-8cc045e6341e',
                
                'DRIVER_AVAILABLE',
                'active',
                35.471403642353955,
                -97.51767019787825,
                'Oklahoma City',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'south',
                '{"direction": "west", "truck_type": "Van", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '638d110f-3c1c-4762-8b83-37fbc111f4e5',
                
                'DRIVER_AVAILABLE',
                'active',
                35.46927778657885,
                -97.52160137821471,
                'Oklahoma City',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'north',
                '{"direction": "west", "truck_type": "20T", "available_hours": 55}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '858753d6-55b3-4aa5-9bca-27199d3f14ab',
                
                'DRIVER_AVAILABLE',
                'active',
                35.49136211647246,
                -97.52815422090391,
                'Oklahoma City',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'south',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ad4267bb-6658-412f-83f0-f94cee0e9411',
                
                'DRIVER_AVAILABLE',
                'active',
                36.18339520540837,
                -95.97026975202799,
                'Tulsa',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'north',
                '{"direction": "south", "truck_type": "Van", "available_hours": 3}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '82bc624c-ac43-4474-9233-e7963ca6d35a',
                
                'DRIVER_AVAILABLE',
                'active',
                36.165580113940536,
                -96.02670912521947,
                'Tulsa',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'north',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                19,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'de930aef-e802-4dba-8360-fb7fcd2ab4cc',
                
                'DRIVER_AVAILABLE',
                'active',
                36.177402654110324,
                -96.00719136953789,
                'Tulsa',
                'United States',
                'Houston',
                'United States',
                29.7604,
                -95.3698,
                'north',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c2bc4b5e-1fd2-4a10-ba9b-8ad41a3e44ce',
                
                'DRIVER_AVAILABLE',
                'active',
                36.18559658413018,
                -95.94897378103168,
                'Tulsa',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'long_haul',
                '{"direction": "west", "truck_type": "20T", "available_hours": 37}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                87,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '8ba8ffbe-3528-4063-b9bd-45360115b181',
                
                'DRIVER_AVAILABLE',
                'active',
                36.203579905612436,
                -95.98659035941006,
                'Tulsa',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '7b416389-ab7a-4ffc-94b2-c8cbd2af7d23',
                
                'DRIVER_AVAILABLE',
                'active',
                36.11643684616669,
                -95.95154717267322,
                'Tulsa',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'long_haul',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4f0e90a8-3bfd-4bd5-bac6-dcbfa095ef38',
                
                'DRIVER_AVAILABLE',
                'active',
                36.185732266944164,
                -95.9681584347474,
                'Tulsa',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'long_haul',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 27}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '2bc4e542-c5b9-4668-8c24-06e54a73dafc',
                
                'DRIVER_AVAILABLE',
                'active',
                36.121398695100424,
                -95.9478511362332,
                'Tulsa',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'long_haul',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                51,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ce86fbcf-4681-45eb-b58c-e69dbd35f109',
                
                'DRIVER_AVAILABLE',
                'active',
                36.12893477349887,
                -95.98264334587185,
                'Tulsa',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '6e9369e0-2e05-4200-9dcc-8d7f6eeac7c6',
                
                'DRIVER_AVAILABLE',
                'active',
                39.07369456916882,
                -94.5948450327485,
                'Kansas City',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'local',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                22,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c1c526e9-e422-46c3-aec3-2e67f6f6e6d9',
                
                'DRIVER_AVAILABLE',
                'active',
                39.104006930085944,
                -94.54800325029838,
                'Kansas City',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'local',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '7842aac3-7899-4e12-96e1-803a63a3a8d6',
                
                'DRIVER_AVAILABLE',
                'active',
                39.08329759295321,
                -94.61510883406397,
                'Kansas City',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 15}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                71,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c0ecdbfd-c406-49ce-b2b7-30aa3a3acf0f',
                
                'DRIVER_AVAILABLE',
                'active',
                39.09061091957757,
                -94.53796877417663,
                'Kansas City',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'north',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                34,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '86e72b35-3b1b-4455-ae05-3ef5e0b62245',
                
                'DRIVER_AVAILABLE',
                'active',
                39.096807823718684,
                -94.6085539645916,
                'Kansas City',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'local',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 35}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                95,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '56eb073f-ff14-4cd6-b38a-a4205eaac6d8',
                
                'DRIVER_AVAILABLE',
                'active',
                39.10204775027254,
                -94.55582986942504,
                'Kansas City',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'local',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '0cdebfcd-17a2-48d7-b5dd-831904acdf4c',
                
                'DRIVER_AVAILABLE',
                'active',
                39.10642969491702,
                -94.58873222831548,
                'Kansas City',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'south',
                '{"direction": "west", "truck_type": "Van", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                96,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '253c74fa-cef5-469b-a242-8fbc6d805e37',
                
                'DRIVER_AVAILABLE',
                'active',
                39.081292216553386,
                -94.57369513503473,
                'Kansas City',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'local',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                21,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '2d04fb56-6b47-4fc9-b28d-e227579a2d30',
                
                'DRIVER_AVAILABLE',
                'active',
                39.057068402968916,
                -94.56758306800603,
                'Kansas City',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'north',
                '{"direction": "east", "truck_type": "20T", "available_hours": 45}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                31,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b232b973-52f4-4a17-8da0-261300b48ea3',
                
                'DRIVER_AVAILABLE',
                'active',
                38.59236055457504,
                -90.22718692373824,
                'St. Louis',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                81,
                1
;
