INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '2590e03d-5871-482b-9603-db83a9963917',
                
                'DRIVER_AVAILABLE',
                'active',
                36.14349782006675,
                -115.15851437062408,
                'Las Vegas',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '172db8ec-f79a-4b22-a483-d0038cc66e1e',
                
                'DRIVER_AVAILABLE',
                'active',
                36.131597505141926,
                -115.11125329538822,
                'Las Vegas',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '43a31cda-f2dd-4a30-aebe-c50a0661fe18',
                
                'DRIVER_AVAILABLE',
                'active',
                36.14210183916443,
                -115.17853782469345,
                'Las Vegas',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'local',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                73,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '02c864ca-93ea-474e-b4a9-eab812a1307c',
                
                'DRIVER_AVAILABLE',
                'active',
                36.1489275562226,
                -115.0925708732904,
                'Las Vegas',
                'United States',
                'Oklahoma City',
                'United States',
                35.4676,
                -97.5164,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 49}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c4b6c24f-3f49-49f2-9d79-152fcc4f7656',
                
                'DRIVER_AVAILABLE',
                'active',
                36.21106793452963,
                -115.0957154116588,
                'Las Vegas',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ebc8d872-f31e-45d4-8031-b099af8920dc',
                
                'DRIVER_AVAILABLE',
                'active',
                36.17831702420381,
                -115.14787770927676,
                'Las Vegas',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'north',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                13,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '256fcebe-6c47-413b-8ceb-7cdcc2aedf61',
                
                'DRIVER_AVAILABLE',
                'active',
                36.199107041291036,
                -115.13370984422237,
                'Las Vegas',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'local',
                '{"direction": "south", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                60,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '75754f61-309a-4f01-b777-cb303664085d',
                
                'DRIVER_AVAILABLE',
                'active',
                36.12154264940415,
                -115.13243209361545,
                'Las Vegas',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'north',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                74,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4715f785-3b5f-4b8f-b504-7d7a2227d1d8',
                
                'DRIVER_AVAILABLE',
                'active',
                33.421460228182994,
                -112.10230265439642,
                'Phoenix',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'south',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 56}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                5,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '46c7733c-7d25-4326-b63d-1deabf708de5',
                
                'DRIVER_AVAILABLE',
                'active',
                33.420286851551474,
                -112.10107012929316,
                'Phoenix',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'north',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                99,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '202711ab-85b8-422a-bb4d-36790c301743',
                
                'DRIVER_AVAILABLE',
                'active',
                33.45157361961028,
                -112.09831322268342,
                'Phoenix',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'long_haul',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4337c714-0fb6-477a-97c2-bfdeae5a549d',
                
                'DRIVER_AVAILABLE',
                'active',
                33.43662536849271,
                -112.0374777000801,
                'Phoenix',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'south',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ef7e3591-dda3-4d0d-8745-bbb7a06ddd4d',
                
                'DRIVER_AVAILABLE',
                'active',
                33.48190151756739,
                -112.07092923857282,
                'Phoenix',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'north',
                '{"direction": "north", "truck_type": "Van", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                41,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '29a3b269-c84b-4812-b7b3-9cb7ce5d0caf',
                
                'DRIVER_AVAILABLE',
                'active',
                32.242947393843345,
                -111.01881906659563,
                'Tucson',
                'United States',
                'Austin',
                'United States',
                30.2672,
                -97.7431,
                'north',
                '{"direction": "south", "truck_type": "20T", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                71,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ee79fe6c-303f-45d4-8031-b099af8920dc',
                
                'DRIVER_AVAILABLE',
                'active',
                32.258353571132005,
                -110.9545716561542,
                'Tucson',
                'United States',
                'Albuquerque',
                'United States',
                35.0844,
                -106.6504,
                'south',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                56,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '705868e7-e80c-4252-8861-05f0ad7e6700',
                
                'DRIVER_AVAILABLE',
                'active',
                32.201807663082064,
                -110.98197217405122,
                'Tucson',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'local',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                66,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '31ff12f3-13a3-4ede-8504-42d91b353b85',
                
                'DRIVER_AVAILABLE',
                'active',
                32.23015944872616,
                -110.96227388087162,
                'Tucson',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'a61b6112-bec7-4f2c-aa37-89e0a7773b6f',
                
                'DRIVER_AVAILABLE',
                'active',
                32.267112747490025,
                -110.92942475493224,
                'Tucson',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'north',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                46,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b62fe23e-cfe2-4af8-9b78-630d34e616ee',
                
                'DRIVER_AVAILABLE',
                'active',
                40.73177255898036,
                -111.89250332997133,
                'Salt Lake City',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'long_haul',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4f17f734-11c7-4b04-ad2a-71c8fee923c7',
                
                'DRIVER_AVAILABLE',
                'active',
                40.73407821280936,
                -111.92367352743732,
                'Salt Lake City',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'north',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                57,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'a8d7b5c7-f5a0-473b-84fd-ff999227f4ee',
                
                'DRIVER_AVAILABLE',
                'active',
                40.8106547628651,
                -111.877362281577,
                'Salt Lake City',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'long_haul',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                34,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'f140ddf2-41bc-4aa4-9ae2-40dcca547702',
                
                'DRIVER_AVAILABLE',
                'active',
                40.754117121017366,
                -111.87602251167002,
                'Salt Lake City',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'south',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                97,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9d086936-a422-4375-ad56-27a1904ced14',
                
                'DRIVER_AVAILABLE',
                'active',
                40.75539583720818,
                -111.91164445825586,
                'Salt Lake City',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'fb006d0a-e07a-4187-978a-e163ff58dd97',
                
                'DRIVER_AVAILABLE',
                'active',
                40.711165165980205,
                -111.8471890863279,
                'Salt Lake City',
                'United States',
                'Jacksonville',
                'United States',
                30.3322,
                -81.6557,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 3}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '6b998f84-0259-49cb-8dbf-02751336cd5d',
                
                'DRIVER_AVAILABLE',
                'active',
                40.79012642358112,
                -111.91690346032566,
                'Salt Lake City',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'south',
                '{"direction": "south", "truck_type": "20T", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                22,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '640d96eb-8b98-4223-8aa6-64b9b0f281a2',
                
                'DRIVER_AVAILABLE',
                'active',
                40.74932302732291,
                -111.89470477554052,
                'Salt Lake City',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'north',
                '{"direction": "west", "truck_type": "20T", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                30,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'd5a4b99b-4312-4ed8-8029-35335d9a848c',
                
                'DRIVER_AVAILABLE',
                'active',
                40.743737841475124,
                -111.92183200988741,
                'Salt Lake City',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'long_haul',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '57c9dd89-47d2-4ceb-be05-95d8dc7cb82e',
                
                'DRIVER_AVAILABLE',
                'active',
                43.60237297138048,
                -116.16931066968934,
                'Boise',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 38}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                6,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ffbb00ca-21d5-4c44-8c3f-8cc045e6341e',
                
                'DRIVER_AVAILABLE',
                'active',
                43.58275183478121,
                -116.20974185647601,
                'Boise',
                'United States',
                'Seattle',
                'United States',
                47.6062,
                -122.3321,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 39}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                94,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '638d110f-3c1c-4762-8b83-37fbc111f4e5',
                
                'DRIVER_AVAILABLE',
                'active',
                43.659918526681814,
                -116.19855979350466,
                'Boise',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                19,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '858753d6-55b3-4aa5-9bca-27199d3f14ab',
                
                'DRIVER_AVAILABLE',
                'active',
                43.583626281196224,
                -116.21360440300664,
                'Boise',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ad4267bb-6658-412f-83f0-f94cee0e9411',
                
                'DRIVER_AVAILABLE',
                'active',
                43.59252317368653,
                -116.19717638761625,
                'Boise',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 49}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '82bc624c-ac43-4474-9233-e7963ca6d35a',
                
                'DRIVER_AVAILABLE',
                'active',
                43.60854159499731,
                -116.24248425336869,
                'Boise',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'local',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 37}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'de930aef-e802-4dba-8360-fb7fcd2ab4cc',
                
                'DRIVER_AVAILABLE',
                'active',
                43.617831835685415,
                -116.17603157352069,
                'Boise',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'north',
                '{"direction": "local", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                76,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c2bc4b5e-1fd2-4a10-ba9b-8ad41a3e44ce',
                
                'DRIVER_AVAILABLE',
                'active',
                43.60025436799159,
                -116.16069910194526,
                'Boise',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                77,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '8ba8ffbe-3528-4063-b9bd-45360115b181',
                
                'DRIVER_AVAILABLE',
                'active',
                43.610141016606306,
                -116.17951979914478,
                'Boise',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                88,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '7b416389-ab7a-4ffc-94b2-c8cbd2af7d23',
                
                'DRIVER_AVAILABLE',
                'active',
                43.641646854657346,
                -116.23474904996586,
                'Boise',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'south',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4f0e90a8-3bfd-4bd5-bac6-dcbfa095ef38',
                
                'DRIVER_AVAILABLE',
                'active',
                47.58746275179726,
                -122.36880582229999,
                'Seattle',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '2bc4e542-c5b9-4668-8c24-06e54a73dafc',
                
                'DRIVER_AVAILABLE',
                'active',
                47.62659329015634,
                -122.33513671261633,
                'Seattle',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'local',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 58}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ce86fbcf-4681-45eb-b58c-e69dbd35f109',
                
                'DRIVER_AVAILABLE',
                'active',
                47.6108131108218,
                -122.37464834159451,
                'Seattle',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'local',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                74,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '6e9369e0-2e05-4200-9dcc-8d7f6eeac7c6',
                
                'DRIVER_AVAILABLE',
                'active',
                47.588183783283974,
                -122.36482371113298,
                'Seattle',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'long_haul',
                '{"direction": "local", "truck_type": "20T", "available_hours": 41}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c1c526e9-e422-46c3-aec3-2e67f6f6e6d9',
                
                'DRIVER_AVAILABLE',
                'active',
                47.639617442905596,
                -122.35012230769973,
                'Seattle',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '7842aac3-7899-4e12-96e1-803a63a3a8d6',
                
                'DRIVER_AVAILABLE',
                'active',
                47.61385118737285,
                -122.34900958388764,
                'Seattle',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                69,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c0ecdbfd-c406-49ce-b2b7-30aa3a3acf0f',
                
                'DRIVER_AVAILABLE',
                'active',
                47.250055542461666,
                -122.41829025967255,
                'Tacoma',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'north',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '86e72b35-3b1b-4455-ae05-3ef5e0b62245',
                
                'DRIVER_AVAILABLE',
                'active',
                47.22592321994998,
                -122.41478047076119,
                'Tacoma',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'north',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 14}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '56eb073f-ff14-4cd6-b38a-a4205eaac6d8',
                
                'DRIVER_AVAILABLE',
                'active',
                47.228531599516195,
                -122.45719810828874,
                'Tacoma',
                'United States',
                'Cincinnati',
                'United States',
                39.1031,
                -84.512,
                'north',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                85,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '0cdebfcd-17a2-48d7-b5dd-831904acdf4c',
                
                'DRIVER_AVAILABLE',
                'active',
                47.27953882556437,
                -122.44650709736604,
                'Tacoma',
                'United States',
                'Omaha',
                'United States',
                41.2565,
                -95.9345,
                'south',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '253c74fa-cef5-469b-a242-8fbc6d805e37',
                
                'DRIVER_AVAILABLE',
                'active',
                47.24755315876866,
                -122.47530277387332,
                'Tacoma',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'south',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '2d04fb56-6b47-4fc9-b28d-e227579a2d30',
                
                'DRIVER_AVAILABLE',
                'active',
                47.27127027297047,
                -122.42269199178797,
                'Tacoma',
                'United States',
                'Dallas',
                'United States',
                32.7767,
                -96.797,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 2}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b232b973-52f4-4a17-8da0-261300b48ea3',
                
                'DRIVER_AVAILABLE',
                'active',
                47.253135785026544,
                -122.4550319035774,
                'Tacoma',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'long_haul',
                '{"direction": "local", "truck_type": "Van", "available_hours": 30}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                0
;
