INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4b01747f-dbb8-4f82-a238-02f466895c20',
                'DRIVER_AVAILABLE',
                'active',
                38.60762451965695,
                -90.17311245030434,
                'St. Louis',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'south',
                '{"direction": "east", "truck_type": "20T", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                67,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'fdb369d3-7160-47ac-96fe-c34c67732147',
                'DRIVER_AVAILABLE',
                'active',
                38.61086912052535,
                -90.17787135273919,
                'St. Louis',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'south',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                59,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '308b4a85-3634-41b4-af3f-216c2232a112',
                'DRIVER_AVAILABLE',
                'active',
                38.60062764851353,
                -90.15129903269447,
                'St. Louis',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'local',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 53}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                12,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'd71b3023-36f7-49a5-8fd6-f20845c23417',
                'DRIVER_AVAILABLE',
                'active',
                38.63707126640988,
                -90.24493537343693,
                'St. Louis',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 40}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                21,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '29b85d29-8a32-4959-af5b-d81848c9167c',
                'DRIVER_AVAILABLE',
                'active',
                38.634988906889646,
                -90.2444252475977,
                'St. Louis',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'south',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                61,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a8a43b97-100a-45ad-bf84-d7ab1f446c03',
                'DRIVER_AVAILABLE',
                'active',
                38.612915790328934,
                -90.2169709942969,
                'St. Louis',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'north',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 16}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                41,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '684fb28a-d4e2-496a-8e4d-75ec6a1b1bc2',
                'DRIVER_AVAILABLE',
                'active',
                41.22268991512139,
                -95.92292525859051,
                'Omaha',
                'United States',
                'St. Louis',
                'United States',
                38.627,
                -90.1994,
                'north',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'cc808e07-3ee3-41c1-869f-49d25aa2c0ef',
                'DRIVER_AVAILABLE',
                'active',
                41.274506306833985,
                -95.89534889667836,
                'Omaha',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '9031761b-f36d-43a7-8d0d-7fba3c268c14',
                'DRIVER_AVAILABLE',
                'active',
                41.29160715013502,
                -95.90925234610333,
                'Omaha',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'north',
                '{"direction": "east", "truck_type": "Van", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'f8388ead-ea2a-4019-abb8-323725ae0419',
                'DRIVER_AVAILABLE',
                'active',
                41.28843812711188,
                -95.91124505628432,
                'Omaha',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 38}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                78,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '3203fb48-a200-461e-8629-7a0745b04cc4',
                'DRIVER_AVAILABLE',
                'active',
                41.25157113894125,
                -95.92411490627546,
                'Omaha',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'north',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                81,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '80b8f09c-a78f-4724-9152-48ff00e1d6c7',
                'DRIVER_AVAILABLE',
                'active',
                41.212472804320875,
                -95.89477972028828,
                'Omaha',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'long_haul',
                '{"direction": "east", "truck_type": "20T", "available_hours": 9}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'eef00239-7bd5-42a2-8bc9-5b22777d279a',
                'DRIVER_AVAILABLE',
                'active',
                41.6107522770638,
                -93.64641813632836,
                'Des Moines',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'local',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '476fc42b-d98b-4382-becc-3f3c2ca32a68',
                'DRIVER_AVAILABLE',
                'active',
                41.5956575289236,
                -93.59936105238957,
                'Des Moines',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '836f8f39-62a0-40ee-b254-8319536fae73',
                'DRIVER_AVAILABLE',
                'active',
                41.54927509959775,
                -93.63931928488137,
                'Des Moines',
                'United States',
                'Indianapolis',
                'United States',
                39.7684,
                -86.1581,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '1f1e311a-f1f0-4adf-ade8-5ad8370c7da9',
                'DRIVER_AVAILABLE',
                'active',
                41.55807104209205,
                -93.57522956873535,
                'Des Moines',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'south',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 52}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'dfc122ee-0d82-47d3-a503-7dc36fe8cbb6',
                'DRIVER_AVAILABLE',
                'active',
                41.55526559146819,
                -93.58624312933567,
                'Des Moines',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'north',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                62,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'fe22ae05-18b2-4e66-a5f4-08359b108a5c',
                'DRIVER_AVAILABLE',
                'active',
                41.559331903893586,
                -93.60928684650554,
                'Des Moines',
                'United States',
                'Salt Lake City',
                'United States',
                40.7608,
                -111.891,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'faca9f35-deca-4b8c-b9c6-70c18a5275ff',
                'DRIVER_AVAILABLE',
                'active',
                41.61923895054273,
                -93.65647118172078,
                'Des Moines',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                97,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '2ed51bef-d0cc-4351-bd41-134a7b776f81',
                'DRIVER_AVAILABLE',
                'active',
                41.56557625818049,
                -93.63195602655684,
                'Des Moines',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                77,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '685998f3-9c26-43a7-8be0-700f14826847',
                'DRIVER_AVAILABLE',
                'active',
                41.58462312739115,
                -93.63833094762413,
                'Des Moines',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'local',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '1d717b72-176e-4a0a-8880-231452e90550',
                'DRIVER_AVAILABLE',
                'active',
                41.63084370474848,
                -93.58471670331316,
                'Des Moines',
                'United States',
                'Houston',
                'United States',
                29.7604,
                -95.3698,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                40,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '5f105a10-8b16-4c51-a3b0-5a2e432f52d3',
                'DRIVER_AVAILABLE',
                'active',
                44.979314838650396,
                -93.26441955663212,
                'Minneapolis',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'south',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                46,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'f4cc7d52-e2df-4822-adbf-42bf3a19e717',
                'DRIVER_AVAILABLE',
                'active',
                44.96214706149658,
                -93.3065658052389,
                'Minneapolis',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'north',
                '{"direction": "west", "truck_type": "Van", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'f8d744c0-7bf9-4bcd-a859-811a406225f0',
                'DRIVER_AVAILABLE',
                'active',
                44.98271655503477,
                -93.29288393346343,
                'Minneapolis',
                'United States',
                'Boston',
                'United States',
                42.3601,
                -71.0589,
                'south',
                '{"direction": "east", "truck_type": "Van", "available_hours": 71}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4f37ec1b-d06b-4df8-9c48-238a0583102c',
                'DRIVER_AVAILABLE',
                'active',
                44.98523115727483,
                -93.24049637780745,
                'Minneapolis',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 33}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                92,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '1d3d17cb-47ce-46a4-b46e-54850a6e6e65',
                'DRIVER_AVAILABLE',
                'active',
                44.94896237169314,
                -93.2694606316504,
                'Minneapolis',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'south',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                55,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e1c19c78-24b8-4489-9c26-88dddcf36305',
                'DRIVER_AVAILABLE',
                'active',
                44.97240496468806,
                -93.22438346276044,
                'Minneapolis',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                61,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'bef989bb-4638-4470-805e-5f3dbf797479',
                'DRIVER_AVAILABLE',
                'active',
                43.05836663777958,
                -87.89459366423729,
                'Milwaukee',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'long_haul',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'be216e25-c220-4a55-9c48-7ccae32c578e',
                'DRIVER_AVAILABLE',
                'active',
                43.010919217882126,
                -87.9491960817368,
                'Milwaukee',
                'United States',
                'Des Moines',
                'United States',
                41.5868,
                -93.625,
                'long_haul',
                '{"direction": "west", "truck_type": "Van", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                77,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '90e99108-53df-4a1f-bd1f-27a72b83f8e4',
                'DRIVER_AVAILABLE',
                'active',
                43.028590967556575,
                -87.88155988181926,
                'Milwaukee',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'south',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 55}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                31,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '845f4039-3841-49a6-9f44-5b5cd3b57747',
                'DRIVER_AVAILABLE',
                'active',
                43.027384102245854,
                -87.90140855392171,
                'Milwaukee',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'long_haul',
                '{"direction": "south", "truck_type": "20T", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '20c894aa-eda5-4cc8-8f79-238eb739ff31',
                'DRIVER_AVAILABLE',
                'active',
                43.0732989698835,
                -87.87271328421582,
                'Milwaukee',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'north',
                '{"direction": "west", "truck_type": "Van", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '81c0e702-993b-4e01-b502-1afb6966cc15',
                'DRIVER_AVAILABLE',
                'active',
                43.06411203133605,
                -87.91114335549116,
                'Milwaukee',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'local',
                '{"direction": "north", "truck_type": "Van", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '22133812-bac8-4574-805d-ae0958d95990',
                'DRIVER_AVAILABLE',
                'active',
                41.91524631962202,
                -87.62879841848715,
                'Chicago',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e7fc0d44-2c72-4e88-be5c-60ffb5d5f2a0',
                'DRIVER_AVAILABLE',
                'active',
                41.87406540555274,
                -87.59424708140001,
                'Chicago',
                'United States',
                'Phoenix',
                'United States',
                33.4484,
                -112.074,
                'long_haul',
                '{"direction": "west", "truck_type": "20T", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                87,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '9666887e-8bd7-48c4-8645-d242fe1253d7',
                'DRIVER_AVAILABLE',
                'active',
                41.88994231390447,
                -87.60965343832602,
                'Chicago',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'north',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'c4c521bb-f9a7-4c62-9bb9-e35024e17ae4',
                'DRIVER_AVAILABLE',
                'active',
                41.92236762218388,
                -87.65772128544874,
                'Chicago',
                'United States',
                'San Antonio',
                'United States',
                29.4241,
                -98.4936,
                'south',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '1d551c87-bd50-4bf1-a350-3e102323c468',
                'DRIVER_AVAILABLE',
                'active',
                41.907354145369794,
                -87.67629240006345,
                'Chicago',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                98,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'df53985d-8f88-445d-8f74-156029468954',
                'DRIVER_AVAILABLE',
                'active',
                41.9109132564868,
                -87.58581180672984,
                'Chicago',
                'United States',
                'San Antonio',
                'United States',
                29.4241,
                -98.4936,
                'south',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ae577db5-5de4-432a-a64c-ff0ca94289cd',
                'DRIVER_AVAILABLE',
                'active',
                41.90288696269153,
                -87.63034919904545,
                'Chicago',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '1e00cb18-9462-4d29-bf8c-077d26f075b8',
                'DRIVER_AVAILABLE',
                'active',
                41.891428719375185,
                -87.65112285532156,
                'Chicago',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                13,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '71e2026a-fe47-46d5-9f2d-cdc01af89f1f',
                'DRIVER_AVAILABLE',
                'active',
                41.84514540085878,
                -87.62983949161196,
                'Chicago',
                'United States',
                'Jacksonville',
                'United States',
                30.3322,
                -81.6557,
                'south',
                '{"direction": "west", "truck_type": "Van", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '01cf6a9f-211f-4c3e-be66-8e7151feec0c',
                'DRIVER_AVAILABLE',
                'active',
                39.72143755845086,
                -86.19529554899391,
                'Indianapolis',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'north',
                '{"direction": "local", "truck_type": "Van", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                38,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'b1989cec-4c41-49d9-b084-5f3a3b49ba6b',
                'DRIVER_AVAILABLE',
                'active',
                39.7605761118669,
                -86.17176645462885,
                'Indianapolis',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'south',
                '{"direction": "east", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '3c1f1f3d-715e-4801-97a6-f70323a31f79',
                'DRIVER_AVAILABLE',
                'active',
                39.76210693796626,
                -86.18244781421873,
                'Indianapolis',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'south',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0107224e-6465-460f-b313-221dbd58cdc9',
                'DRIVER_AVAILABLE',
                'active',
                39.79683936327103,
                -86.164825919789,
                'Indianapolis',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '3482f56c-0cc3-47d0-9954-7dbf9e0bed5f',
                'DRIVER_AVAILABLE',
                'active',
                39.72219780480169,
                -86.15069062662351,
                'Indianapolis',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'local',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                96,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'adf2067e-15ce-42cc-ab83-c55626adc9ed',
                'DRIVER_AVAILABLE',
                'active',
                39.75737779387072,
                -86.1872612828604,
                'Indianapolis',
                'United States',
                'Des Moines',
                'United States',
                41.5868,
                -93.625,
                'north',
                '{"direction": "south", "truck_type": "Van", "available_hours": 57}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                25,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '70a36451-3df8-45a5-b23e-7929dc5e43aa',
                'DRIVER_AVAILABLE',
                'active',
                42.29417717332753,
                -83.02705199397404,
                'Detroit',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'local',
                '{"direction": "south", "truck_type": "20T", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                2
            );