INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '2590e03d-5871-482b-9603-db83a9963917',
                
                'DRIVER_AVAILABLE',
                'active',
                28.559771138412188,
                -81.3786187848897,
                'Orlando',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'long_haul',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 1}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                88,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '172db8ec-f79a-4b22-a483-d0038cc66e1e',
                
                'DRIVER_AVAILABLE',
                'active',
                28.561823095695537,
                -81.42670416339692,
                'Orlando',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'local',
                '{"direction": "local", "truck_type": "20T", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                84,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '43a31cda-f2dd-4a30-aebe-c50a0661fe18',
                
                'DRIVER_AVAILABLE',
                'active',
                40.45801106546274,
                -80.03381646527083,
                'Pittsburgh',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'north',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                78,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '02c864ca-93ea-474e-b4a9-eab812a1307c',
                
                'DRIVER_AVAILABLE',
                'active',
                40.45480633089833,
                -80.01662596050083,
                'Pittsburgh',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'long_haul',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 45}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c4b6c24f-3f49-49f2-9d79-152fcc4f7656',
                
                'DRIVER_AVAILABLE',
                'active',
                40.422191213856266,
                -80.02305657947586,
                'Pittsburgh',
                'United States',
                'Phoenix',
                'United States',
                33.4484,
                -112.074,
                'north',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                15,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ebc8d872-f31e-45d4-8031-b099af8920dc',
                
                'DRIVER_AVAILABLE',
                'active',
                40.467902072523636,
                -79.99854058282871,
                'Pittsburgh',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'south',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '256fcebe-6c47-413b-8ceb-7cdcc2aedf61',
                
                'DRIVER_AVAILABLE',
                'active',
                40.48879057887374,
                -79.99512144361175,
                'Pittsburgh',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'long_haul',
                '{"direction": "east", "truck_type": "20T", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '75754f61-309a-4f01-b777-cb303664085d',
                
                'DRIVER_AVAILABLE',
                'active',
                40.408835300470365,
                -80.00557850365308,
                'Pittsburgh',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'north',
                '{"direction": "west", "truck_type": "20T", "available_hours": 33}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4715f785-3b5f-4b8f-b504-7d7a2227d1d8',
                
                'DRIVER_AVAILABLE',
                'active',
                40.48325206388148,
                -79.98874649702886,
                'Pittsburgh',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'long_haul',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '46c7733c-7d25-4326-b63d-1deabf708de5',
                
                'DRIVER_AVAILABLE',
                'active',
                40.41559063167258,
                -80.00844267802263,
                'Pittsburgh',
                'United States',
                'Houston',
                'United States',
                29.7604,
                -95.3698,
                'south',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '202711ab-85b8-422a-bb4d-36790c301743',
                
                'DRIVER_AVAILABLE',
                'active',
                39.94959007828746,
                -75.16458039206628,
                'Philadelphia',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'north',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4337c714-0fb6-477a-97c2-bfdeae5a549d',
                
                'DRIVER_AVAILABLE',
                'active',
                39.93435743901617,
                -75.14999503841895,
                'Philadelphia',
                'United States',
                'Stockton',
                'United States',
                37.9577,
                -121.2908,
                'local',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                88,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ef7e3591-dda3-4d0d-8745-bbb7a06ddd4d',
                
                'DRIVER_AVAILABLE',
                'active',
                39.97726982602678,
                -75.15565102105752,
                'Philadelphia',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'north',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 27}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                26,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '29a3b269-c84b-4812-b7b3-9cb7ce5d0caf',
                
                'DRIVER_AVAILABLE',
                'active',
                39.91501748213135,
                -75.15972452648252,
                'Philadelphia',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'local',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                85,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ee79fe6c-303f-45d4-8031-b099af8920dc',
                
                'DRIVER_AVAILABLE',
                'active',
                39.97137207069489,
                -75.2066767386773,
                'Philadelphia',
                'United States',
                'Miami',
                'United States',
                25.7617,
                -80.1918,
                'south',
                '{"direction": "north", "truck_type": "Van", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                99,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '705868e7-e80c-4252-8861-05f0ad7e6700',
                
                'DRIVER_AVAILABLE',
                'active',
                39.90893901953273,
                -75.20575323070028,
                'Philadelphia',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 51}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                19,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '31ff12f3-13a3-4ede-8504-42d91b353b85',
                
                'DRIVER_AVAILABLE',
                'active',
                39.96549917695557,
                -75.14546029441554,
                'Philadelphia',
                'United States',
                'Fort Worth',
                'United States',
                32.7555,
                -97.3308,
                'north',
                '{"direction": "local", "truck_type": "Van", "available_hours": 60}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'a61b6112-bec7-4f2c-aa37-89e0a7773b6f',
                
                'DRIVER_AVAILABLE',
                'active',
                39.91998163440152,
                -75.19055095882307,
                'Philadelphia',
                'United States',
                'Albuquerque',
                'United States',
                35.0844,
                -106.6504,
                'south',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 3}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                88,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b62fe23e-cfe2-4af8-9b78-630d34e616ee',
                
                'DRIVER_AVAILABLE',
                'active',
                39.967504776398435,
                -75.18846124518075,
                'Philadelphia',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4f17f734-11c7-4b04-ad2a-71c8fee923c7',
                
                'DRIVER_AVAILABLE',
                'active',
                39.92623017712208,
                -75.13701977497469,
                'Philadelphia',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'south',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 47}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                82,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'a8d7b5c7-f5a0-473b-84fd-ff999227f4ee',
                
                'DRIVER_AVAILABLE',
                'active',
                40.702713235024056,
                -74.01614525852061,
                'New York',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'local',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 60}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'f140ddf2-41bc-4aa4-9ae2-40dcca547702',
                
                'DRIVER_AVAILABLE',
                'active',
                40.72779779751637,
                -73.97793608917421,
                'New York',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 16}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                81,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9d086936-a422-4375-ad56-27a1904ced14',
                
                'DRIVER_AVAILABLE',
                'active',
                40.703009924546045,
                -74.00160672045126,
                'New York',
                'United States',
                'Fort Worth',
                'United States',
                32.7555,
                -97.3308,
                'north',
                '{"direction": "local", "truck_type": "20T", "available_hours": 30}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                76,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'fb006d0a-e07a-4187-978a-e163ff58dd97',
                
                'DRIVER_AVAILABLE',
                'active',
                40.680725301342356,
                -74.02027481666349,
                'New York',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'local',
                '{"direction": "north", "truck_type": "20T", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '6b998f84-0259-49cb-8dbf-02751336cd5d',
                
                'DRIVER_AVAILABLE',
                'active',
                40.705172294985225,
                -74.00283092298105,
                'New York',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'local',
                '{"direction": "north", "truck_type": "20T", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '640d96eb-8b98-4223-8aa6-64b9b0f281a2',
                
                'DRIVER_AVAILABLE',
                'active',
                40.762232415713854,
                -74.04143298817858,
                'New York',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'north',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                4,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'd5a4b99b-4312-4ed8-8029-35335d9a848c',
                
                'DRIVER_AVAILABLE',
                'active',
                40.722896543823076,
                -74.04615587662522,
                'New York',
                'United States',
                'Dallas',
                'United States',
                32.7767,
                -96.797,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 2}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '57c9dd89-47d2-4ceb-be05-95d8dc7cb82e',
                
                'DRIVER_AVAILABLE',
                'active',
                40.750223691461656,
                -73.97330287117455,
                'New York',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'local',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                7,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ffbb00ca-21d5-4c44-8c3f-8cc045e6341e',
                
                'DRIVER_AVAILABLE',
                'active',
                42.409535374475624,
                -71.0556729696467,
                'Boston',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 18}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '638d110f-3c1c-4762-8b83-37fbc111f4e5',
                
                'DRIVER_AVAILABLE',
                'active',
                42.38102930012739,
                -71.00926099737832,
                'Boston',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'long_haul',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 35}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                12,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '858753d6-55b3-4aa5-9bca-27199d3f14ab',
                
                'DRIVER_AVAILABLE',
                'active',
                42.40794437803896,
                -71.03768415237359,
                'Boston',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'north',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 6}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                1,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ad4267bb-6658-412f-83f0-f94cee0e9411',
                
                'DRIVER_AVAILABLE',
                'active',
                42.37870501012832,
                -71.03714805037148,
                'Boston',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'north',
                '{"direction": "local", "truck_type": "20T", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                86,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '82bc624c-ac43-4474-9233-e7963ca6d35a',
                
                'DRIVER_AVAILABLE',
                'active',
                42.32733029200601,
                -71.10883412241087,
                'Boston',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'local',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                21,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'de930aef-e802-4dba-8360-fb7fcd2ab4cc',
                
                'DRIVER_AVAILABLE',
                'active',
                42.34537320923199,
                -71.03787941312618,
                'Boston',
                'United States',
                'Cincinnati',
                'United States',
                39.1031,
                -84.512,
                'local',
                '{"direction": "south", "truck_type": "20T", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                80,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c2bc4b5e-1fd2-4a10-ba9b-8ad41a3e44ce',
                
                'DRIVER_AVAILABLE',
                'active',
                42.33395219150402,
                -71.05545079107962,
                'Boston',
                'United States',
                'Cincinnati',
                'United States',
                39.1031,
                -84.512,
                'south',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 30}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                5,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '8ba8ffbe-3528-4063-b9bd-45360115b181',
                
                'DRIVER_AVAILABLE',
                'active',
                42.38265575822369,
                -71.03673168137135,
                'Boston',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'north',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                66,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '7b416389-ab7a-4ffc-94b2-c8cbd2af7d23',
                
                'DRIVER_AVAILABLE',
                'active',
                39.294119733323285,
                -76.58529931525055,
                'Baltimore',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'local',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4f0e90a8-3bfd-4bd5-bac6-dcbfa095ef38',
                
                'DRIVER_AVAILABLE',
                'active',
                39.327829059517875,
                -76.61498189615355,
                'Baltimore',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'local',
                '{"direction": "east", "truck_type": "20T", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                2,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '2bc4e542-c5b9-4668-8c24-06e54a73dafc',
                
                'DRIVER_AVAILABLE',
                'active',
                39.2943253388527,
                -76.59285134139137,
                'Baltimore',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'south',
                '{"direction": "south", "truck_type": "20T", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                4,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ce86fbcf-4681-45eb-b58c-e69dbd35f109',
                
                'DRIVER_AVAILABLE',
                'active',
                39.29963614210284,
                -76.65073448365582,
                'Baltimore',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'south',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                5,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '6e9369e0-2e05-4200-9dcc-8d7f6eeac7c6',
                
                'DRIVER_AVAILABLE',
                'active',
                39.26289059711362,
                -76.60766395849582,
                'Baltimore',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'north',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                38,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c1c526e9-e422-46c3-aec3-2e67f6f6e6d9',
                
                'DRIVER_AVAILABLE',
                'active',
                38.93081679276234,
                -77.05750639611361,
                'Washington',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'local',
                '{"direction": "south", "truck_type": "20T", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '7842aac3-7899-4e12-96e1-803a63a3a8d6',
                
                'DRIVER_AVAILABLE',
                'active',
                38.94742393652508,
                -77.07314886146865,
                'Washington',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 28}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c0ecdbfd-c406-49ce-b2b7-30aa3a3acf0f',
                
                'DRIVER_AVAILABLE',
                'active',
                38.86897497290612,
                -77.04362482711967,
                'Washington',
                'United States',
                'Austin',
                'United States',
                30.2672,
                -97.7431,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '86e72b35-3b1b-4455-ae05-3ef5e0b62245',
                
                'DRIVER_AVAILABLE',
                'active',
                38.943643300626505,
                -77.00853742040567,
                'Washington',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'south',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '56eb073f-ff14-4cd6-b38a-a4205eaac6d8',
                
                'DRIVER_AVAILABLE',
                'active',
                38.894967898562925,
                -77.08504785157261,
                'Washington',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 5}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '0cdebfcd-17a2-48d7-b5dd-831904acdf4c',
                
                'DRIVER_AVAILABLE',
                'active',
                38.86263067720221,
                -77.05283747938309,
                'Washington',
                'United States',
                'Des Moines',
                'United States',
                41.5868,
                -93.625,
                'long_haul',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '253c74fa-cef5-469b-a242-8fbc6d805e37',
                
                'DRIVER_AVAILABLE',
                'active',
                38.90882465397869,
                -77.04576813618503,
                'Washington',
                'United States',
                'Stockton',
                'United States',
                37.9577,
                -121.2908,
                'long_haul',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 55}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '2d04fb56-6b47-4fc9-b28d-e227579a2d30',
                
                'DRIVER_AVAILABLE',
                'active',
                38.943627368556506,
                -77.01218791001222,
                'Washington',
                'United States',
                'Jacksonville',
                'United States',
                30.3322,
                -81.6557,
                'long_haul',
                '{"direction": "south", "truck_type": "Van", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                26,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b232b973-52f4-4a17-8da0-261300b48ea3',
                
                'DRIVER_AVAILABLE',
                'active',
                38.907189947513544,
                -77.03990693766643,
                'Washington',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'long_haul',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                31,
                4
;
