INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '21b47c07-49a1-431b-9475-83057f4c350b',
                'DRIVER_AVAILABLE',
                'active',
                29.734792467247196,
                -95.35151684403633,
                'Houston',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'north',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                85,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6d3ef0a4-9b9d-44bb-8376-0f9736465528',
                'DRIVER_AVAILABLE',
                'active',
                29.777265139205625,
                -95.40575764335203,
                'Houston',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                45,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '1473f0e5-7d1f-4ecc-a9ad-c2e1d4a4b4c6',
                'DRIVER_AVAILABLE',
                'active',
                29.74771099213569,
                -95.33883200496105,
                'Houston',
                'United States',
                'Seattle',
                'United States',
                47.6062,
                -122.3321,
                'south',
                '{"direction": "west", "truck_type": "20T", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '49232d15-8f5d-4019-8459-52532fae3d3c',
                'DRIVER_AVAILABLE',
                'active',
                29.778743668834625,
                -95.34765608752414,
                'Houston',
                'United States',
                'Detroit',
                'United States',
                42.3314,
                -83.0458,
                'long_haul',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                43,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ed9197cb-e79b-4ed1-a637-ff0814d8db39',
                'DRIVER_AVAILABLE',
                'active',
                29.429577486021117,
                -98.51228818188787,
                'San Antonio',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'local',
                '{"direction": "north", "truck_type": "Van", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                95,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '718318ae-3829-4534-9650-d426892d2110',
                'DRIVER_AVAILABLE',
                'active',
                29.436616801412463,
                -98.52192533193005,
                'San Antonio',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'north',
                '{"direction": "south", "truck_type": "20T", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                69,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '21f7a0a9-2c03-492a-bd38-65194f893870',
                'DRIVER_AVAILABLE',
                'active',
                29.40125645343186,
                -98.51119479090472,
                'San Antonio',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'south',
                '{"direction": "local", "truck_type": "Van", "available_hours": 57}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6da52259-3a5d-4e14-9668-470e07e4e473',
                'DRIVER_AVAILABLE',
                'active',
                29.38867652558365,
                -98.46304309731235,
                'San Antonio',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '042a5b2c-ba73-48c9-a6ac-c9dd924e4ade',
                'DRIVER_AVAILABLE',
                'active',
                29.47170507899308,
                -98.5167336057501,
                'San Antonio',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                17,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '8d9e1ca1-73be-4d4e-a0ba-c33f76123b33',
                'DRIVER_AVAILABLE',
                'active',
                29.376307526927267,
                -98.47415429898429,
                'San Antonio',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'c5355d92-2344-414c-9e9f-ca7cdfba70b2',
                'DRIVER_AVAILABLE',
                'active',
                30.301290887584518,
                -97.70110549603295,
                'Austin',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'local',
                '{"direction": "north", "truck_type": "20T", "available_hours": 9}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'd834f0e8-8dc6-415f-b9a2-6434cad1ad88',
                'DRIVER_AVAILABLE',
                'active',
                30.24702051250972,
                -97.7765190167603,
                'Austin',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                79,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4b7e7b02-9015-4419-b2c6-2fd42c9012e4',
                'DRIVER_AVAILABLE',
                'active',
                30.248193247643407,
                -97.73717836768542,
                'Austin',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6fee0c32-f00f-4752-abed-e078716a980c',
                'DRIVER_AVAILABLE',
                'active',
                30.246341257113276,
                -97.74793994470527,
                'Austin',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'local',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0e20637b-155a-433e-a51d-363af6d44c69',
                'DRIVER_AVAILABLE',
                'active',
                30.219615140658796,
                -97.77404160551278,
                'Austin',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'south',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                73,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e02ee152-5fe8-4e51-801a-4ad5a300d30c',
                'DRIVER_AVAILABLE',
                'active',
                30.315087655638436,
                -97.70717453156877,
                'Austin',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'north',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                98,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e696a89e-c370-4ce8-8df1-460746afedc4',
                'DRIVER_AVAILABLE',
                'active',
                27.53748123140756,
                -99.49998051400571,
                'Laredo',
                'United States',
                'Austin',
                'United States',
                30.2672,
                -97.7431,
                'north',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '7f112d5b-9840-4cff-adc0-265ff2523a6c',
                'DRIVER_AVAILABLE',
                'active',
                27.492404040446303,
                -99.52621907108112,
                'Laredo',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'local',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 58}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                79,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a5977239-9a61-4a89-bb9c-1956c6106f1e',
                'DRIVER_AVAILABLE',
                'active',
                27.50078616524217,
                -99.51366303054797,
                'Laredo',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'north',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '8a29585a-0230-46ba-9c1e-3c498c5b47c6',
                'DRIVER_AVAILABLE',
                'active',
                27.57764195648477,
                -99.49914394944315,
                'Laredo',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'north',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 1}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                79,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0ce1f6ae-318d-45bb-a49c-d70b836b41ee',
                'DRIVER_AVAILABLE',
                'active',
                27.51739156195533,
                -99.51744204849668,
                'Laredo',
                'United States',
                'San Antonio',
                'United States',
                29.4241,
                -98.4936,
                'local',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 2}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '85255c90-ace3-49e4-960b-475dbf3175f6',
                'DRIVER_AVAILABLE',
                'active',
                27.57640213909522,
                -99.50678838961232,
                'Laredo',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'local',
                '{"direction": "west", "truck_type": "20T", "available_hours": 39}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                12,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '84c266d0-0877-42df-9f51-7d04de62f752',
                'DRIVER_AVAILABLE',
                'active',
                27.498463289580894,
                -99.49003280550629,
                'Laredo',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'local',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'cb03f84f-c631-4d85-9538-140c129438d1',
                'DRIVER_AVAILABLE',
                'active',
                27.499908147989448,
                -99.52007167831846,
                'Laredo',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'local',
                '{"direction": "local", "truck_type": "20T", "available_hours": 49}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                49,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '064bbf1c-97ee-4bed-9d79-07d35fcd6b7c',
                'DRIVER_AVAILABLE',
                'active',
                27.51682022484712,
                -99.49486489203761,
                'Laredo',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'local',
                '{"direction": "north", "truck_type": "20T", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                95,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '69a5a854-ed0b-4c80-8ac5-175e752971ad',
                'DRIVER_AVAILABLE',
                'active',
                27.54106229482474,
                -99.43438940903457,
                'Laredo',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a3fefdd9-3677-4810-b7dc-16c284f5599a',
                'DRIVER_AVAILABLE',
                'active',
                35.46874538132681,
                -97.5440450127037,
                'Oklahoma City',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '38da3a97-1e21-41fd-9b83-844f2cb52de4',
                'DRIVER_AVAILABLE',
                'active',
                35.47979901619702,
                -97.5605768111425,
                'Oklahoma City',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'long_haul',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 9}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0cf3c746-17bc-4556-b6be-b3f7d820fc05',
                'DRIVER_AVAILABLE',
                'active',
                35.471403642353955,
                -97.51767019787825,
                'Oklahoma City',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'south',
                '{"direction": "west", "truck_type": "Van", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ab0374e1-52c5-44b4-b79e-d287cff382ec',
                'DRIVER_AVAILABLE',
                'active',
                35.46927778657885,
                -97.52160137821471,
                'Oklahoma City',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'north',
                '{"direction": "west", "truck_type": "20T", "available_hours": 55}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a0d0d0a2-cb0a-4b86-9c18-faad71c8e0e0',
                'DRIVER_AVAILABLE',
                'active',
                35.49136211647246,
                -97.52815422090391,
                'Oklahoma City',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'south',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'c26eaa11-0327-4cff-9b52-df3addbdd8a4',
                'DRIVER_AVAILABLE',
                'active',
                36.18339520540837,
                -95.97026975202799,
                'Tulsa',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'north',
                '{"direction": "south", "truck_type": "Van", "available_hours": 3}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '16c5d384-2d59-4d7d-b72e-8a2289cf1b61',
                'DRIVER_AVAILABLE',
                'active',
                36.165580113940536,
                -96.02670912521947,
                'Tulsa',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'north',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                19,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '2a0e79f8-56f2-44be-bcd3-df13b0fa4656',
                'DRIVER_AVAILABLE',
                'active',
                36.177402654110324,
                -96.00719136953789,
                'Tulsa',
                'United States',
                'Houston',
                'United States',
                29.7604,
                -95.3698,
                'north',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '05cb62fd-0b6b-4442-9021-6d6ded78c273',
                'DRIVER_AVAILABLE',
                'active',
                36.18559658413018,
                -95.94897378103168,
                'Tulsa',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'long_haul',
                '{"direction": "west", "truck_type": "20T", "available_hours": 37}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                87,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '41d857c9-fc92-4725-b9f0-255e66a1679a',
                'DRIVER_AVAILABLE',
                'active',
                36.203579905612436,
                -95.98659035941006,
                'Tulsa',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e980790b-7a4d-41ce-a583-04bb8ef30d2f',
                'DRIVER_AVAILABLE',
                'active',
                36.11643684616669,
                -95.95154717267322,
                'Tulsa',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'long_haul',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4972077f-a2b4-4fc9-8fe2-45ba71aacf53',
                'DRIVER_AVAILABLE',
                'active',
                36.185732266944164,
                -95.9681584347474,
                'Tulsa',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'long_haul',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 27}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '5bc1c212-ed6b-4b19-b283-f7b509d5dc26',
                'DRIVER_AVAILABLE',
                'active',
                36.121398695100424,
                -95.9478511362332,
                'Tulsa',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'long_haul',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                51,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '32e743e3-bef6-4860-8f09-e37304c0a47f',
                'DRIVER_AVAILABLE',
                'active',
                36.12893477349887,
                -95.98264334587185,
                'Tulsa',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '2aaed6ae-3160-41a3-8810-a1140b6b0c99',
                'DRIVER_AVAILABLE',
                'active',
                39.07369456916882,
                -94.5948450327485,
                'Kansas City',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'local',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                22,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '24bf3dbc-5ce6-4938-bc74-ddfb8bc83a92',
                'DRIVER_AVAILABLE',
                'active',
                39.104006930085944,
                -94.54800325029838,
                'Kansas City',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'local',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'f0a370d2-15b4-4713-94cf-1ffa576b17ad',
                'DRIVER_AVAILABLE',
                'active',
                39.08329759295321,
                -94.61510883406397,
                'Kansas City',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 15}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                71,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '8bb5b88c-2a91-4def-a42b-90661e7feb78',
                'DRIVER_AVAILABLE',
                'active',
                39.09061091957757,
                -94.53796877417663,
                'Kansas City',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'north',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                34,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '034b7e63-adc7-451a-ab54-9e45cc25eb23',
                'DRIVER_AVAILABLE',
                'active',
                39.096807823718684,
                -94.6085539645916,
                'Kansas City',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'local',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 35}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                95,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '9275e7b9-5ec9-43d6-8bc2-f34882f55d67',
                'DRIVER_AVAILABLE',
                'active',
                39.10204775027254,
                -94.55582986942504,
                'Kansas City',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'local',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'c6ae65c7-ce3e-485a-a8cd-53e63d214bad',
                'DRIVER_AVAILABLE',
                'active',
                39.10642969491702,
                -94.58873222831548,
                'Kansas City',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'south',
                '{"direction": "west", "truck_type": "Van", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                96,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '39c5eb8e-6ef3-4732-a516-90fc0a4b39ee',
                'DRIVER_AVAILABLE',
                'active',
                39.081292216553386,
                -94.57369513503473,
                'Kansas City',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'local',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                21,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'f7fac6ee-c77d-42f5-bdb0-8613256663f8',
                'DRIVER_AVAILABLE',
                'active',
                39.057068402968916,
                -94.56758306800603,
                'Kansas City',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'north',
                '{"direction": "east", "truck_type": "20T", "available_hours": 45}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                31,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '7012a329-ce53-4ae3-a42f-98381ea07a5d',
                'DRIVER_AVAILABLE',
                'active',
                38.59236055457504,
                -90.22718692373824,
                'St. Louis',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                81,
                1
            );