INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6380f19d-83e8-43da-92b8-954374af6c74',
                'DRIVER_AVAILABLE',
                'active',
                36.14349782006675,
                -115.15851437062408,
                'Las Vegas',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'b5b3d473-874b-47b7-b1f6-16287e7201e9',
                'DRIVER_AVAILABLE',
                'active',
                36.131597505141926,
                -115.11125329538822,
                'Las Vegas',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '736f73f9-9d8e-463e-8fdf-4094d60dc83b',
                'DRIVER_AVAILABLE',
                'active',
                36.14210183916443,
                -115.17853782469345,
                'Las Vegas',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'local',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                73,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '38a4f5cd-998b-479e-be90-d051137ae694',
                'DRIVER_AVAILABLE',
                'active',
                36.1489275562226,
                -115.0925708732904,
                'Las Vegas',
                'United States',
                'Oklahoma City',
                'United States',
                35.4676,
                -97.5164,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 49}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0368e968-a56c-4c42-81c6-6bd252dc583d',
                'DRIVER_AVAILABLE',
                'active',
                36.21106793452963,
                -115.0957154116588,
                'Las Vegas',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                33,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '9fe408ed-5b25-4bfa-93b0-a7242195a8ad',
                'DRIVER_AVAILABLE',
                'active',
                36.17831702420381,
                -115.14787770927676,
                'Las Vegas',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'north',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                13,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0a1c0615-29ed-4a50-9ffa-5efa40d1b333',
                'DRIVER_AVAILABLE',
                'active',
                36.199107041291036,
                -115.13370984422237,
                'Las Vegas',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'local',
                '{"direction": "south", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                60,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '995c8673-ffb6-444e-9b5d-ec6435c3a32c',
                'DRIVER_AVAILABLE',
                'active',
                36.12154264940415,
                -115.13243209361545,
                'Las Vegas',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'north',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                74,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'edb98a71-3e94-49af-9ec0-0ad49ebaa067',
                'DRIVER_AVAILABLE',
                'active',
                33.421460228182994,
                -112.10230265439642,
                'Phoenix',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'south',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 56}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                5,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0f41cce6-a1be-4ccf-aee2-627c522d2c74',
                'DRIVER_AVAILABLE',
                'active',
                33.420286851551474,
                -112.10107012929316,
                'Phoenix',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'north',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                99,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '85828621-95e7-4bd7-ad35-b8923813883f',
                'DRIVER_AVAILABLE',
                'active',
                33.45157361961028,
                -112.09831322268342,
                'Phoenix',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'long_haul',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ba135b49-ef38-4833-962a-3355efb983c1',
                'DRIVER_AVAILABLE',
                'active',
                33.43662536849271,
                -112.0374777000801,
                'Phoenix',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'south',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '84f25660-5dee-4fff-88c4-51c32844f188',
                'DRIVER_AVAILABLE',
                'active',
                33.48190151756739,
                -112.07092923857282,
                'Phoenix',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'north',
                '{"direction": "north", "truck_type": "Van", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                41,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '068556ae-8621-4b43-b119-8019c0a935b9',
                'DRIVER_AVAILABLE',
                'active',
                32.242947393843345,
                -111.01881906659563,
                'Tucson',
                'United States',
                'Austin',
                'United States',
                30.2672,
                -97.7431,
                'north',
                '{"direction": "south", "truck_type": "20T", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                71,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'b33ceacf-32b1-4748-8422-98f67e0aba7f',
                'DRIVER_AVAILABLE',
                'active',
                32.258353571132005,
                -110.9545716561542,
                'Tucson',
                'United States',
                'Albuquerque',
                'United States',
                35.0844,
                -106.6504,
                'south',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                56,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6ec22b06-984d-44a1-bc7d-4ed9254a9884',
                'DRIVER_AVAILABLE',
                'active',
                32.201807663082064,
                -110.98197217405122,
                'Tucson',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'local',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                66,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '2ff2eed8-0a1e-4465-9fd2-0f962b1036a4',
                'DRIVER_AVAILABLE',
                'active',
                32.23015944872616,
                -110.96227388087162,
                'Tucson',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ed59f643-3a4b-468a-829d-792d200b2214',
                'DRIVER_AVAILABLE',
                'active',
                32.267112747490025,
                -110.92942475493224,
                'Tucson',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'north',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                46,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '1df14abc-3b11-4697-b829-98fc57f82085',
                'DRIVER_AVAILABLE',
                'active',
                40.73177255898036,
                -111.89250332997133,
                'Salt Lake City',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'long_haul',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ef9e03c7-4ddb-4cd7-bc02-37503bacafdf',
                'DRIVER_AVAILABLE',
                'active',
                40.73407821280936,
                -111.92367352743732,
                'Salt Lake City',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'north',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                57,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '850f8f85-a4b0-41e3-a122-4739ec58d2fa',
                'DRIVER_AVAILABLE',
                'active',
                40.8106547628651,
                -111.877362281577,
                'Salt Lake City',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'long_haul',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                34,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '108cac40-8755-498c-8f67-bc8085c578f9',
                'DRIVER_AVAILABLE',
                'active',
                40.754117121017366,
                -111.87602251167002,
                'Salt Lake City',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'south',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                97,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'dcf7efee-7c7c-4f91-9bae-e9ce464a1dd9',
                'DRIVER_AVAILABLE',
                'active',
                40.75539583720818,
                -111.91164445825586,
                'Salt Lake City',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ff96bf5d-b616-40ec-abce-21014ec97c3d',
                'DRIVER_AVAILABLE',
                'active',
                40.711165165980205,
                -111.8471890863279,
                'Salt Lake City',
                'United States',
                'Jacksonville',
                'United States',
                30.3322,
                -81.6557,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 3}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'afd43784-b865-4568-be21-90b9889452da',
                'DRIVER_AVAILABLE',
                'active',
                40.79012642358112,
                -111.91690346032566,
                'Salt Lake City',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'south',
                '{"direction": "south", "truck_type": "20T", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                22,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '57796275-2b56-4de2-b2ab-5d96b394c65f',
                'DRIVER_AVAILABLE',
                'active',
                40.74932302732291,
                -111.89470477554052,
                'Salt Lake City',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'north',
                '{"direction": "west", "truck_type": "20T", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                30,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '32344b19-97d6-423e-af30-6ed23b5f59fb',
                'DRIVER_AVAILABLE',
                'active',
                40.743737841475124,
                -111.92183200988741,
                'Salt Lake City',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'long_haul',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'da05e715-382d-4d1d-97cf-8e1d85563eb2',
                'DRIVER_AVAILABLE',
                'active',
                43.60237297138048,
                -116.16931066968934,
                'Boise',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 38}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                6,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4b109f15-b79f-4493-a63e-726e5ce6b93a',
                'DRIVER_AVAILABLE',
                'active',
                43.58275183478121,
                -116.20974185647601,
                'Boise',
                'United States',
                'Seattle',
                'United States',
                47.6062,
                -122.3321,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 39}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                94,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6ef5a481-fdb8-49a9-80eb-38498619201c',
                'DRIVER_AVAILABLE',
                'active',
                43.659918526681814,
                -116.19855979350466,
                'Boise',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                19,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '8d83b33a-1ea0-46ce-9748-aee65004b8f5',
                'DRIVER_AVAILABLE',
                'active',
                43.583626281196224,
                -116.21360440300664,
                'Boise',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'c4edb486-d92c-411c-95a7-cf2e6df29944',
                'DRIVER_AVAILABLE',
                'active',
                43.59252317368653,
                -116.19717638761625,
                'Boise',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 49}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '70da139b-ed4c-4f19-ac6e-3c6f7efd2efc',
                'DRIVER_AVAILABLE',
                'active',
                43.60854159499731,
                -116.24248425336869,
                'Boise',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'local',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 37}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a54f3888-9a5d-4b3a-97f3-2e8f30145528',
                'DRIVER_AVAILABLE',
                'active',
                43.617831835685415,
                -116.17603157352069,
                'Boise',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'north',
                '{"direction": "local", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                76,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4385c5c4-2544-41cd-8ee8-2c1b8b830f95',
                'DRIVER_AVAILABLE',
                'active',
                43.60025436799159,
                -116.16069910194526,
                'Boise',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                77,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '5f84ef2c-b9ec-4c27-95de-8bc228302c94',
                'DRIVER_AVAILABLE',
                'active',
                43.610141016606306,
                -116.17951979914478,
                'Boise',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                88,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '71141975-98fd-42aa-8527-c84c2965753a',
                'DRIVER_AVAILABLE',
                'active',
                43.641646854657346,
                -116.23474904996586,
                'Boise',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'south',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0c3df06b-f67a-436e-996f-593736ee4c35',
                'DRIVER_AVAILABLE',
                'active',
                47.58746275179726,
                -122.36880582229999,
                'Seattle',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4cce49a1-21ec-4324-8ef0-6137ff461457',
                'DRIVER_AVAILABLE',
                'active',
                47.62659329015634,
                -122.33513671261633,
                'Seattle',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'local',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 58}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'd0c07870-579d-4aa2-ae00-235dc5731713',
                'DRIVER_AVAILABLE',
                'active',
                47.6108131108218,
                -122.37464834159451,
                'Seattle',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'local',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                74,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '071af515-5379-4513-86b2-a15a7291ba08',
                'DRIVER_AVAILABLE',
                'active',
                47.588183783283974,
                -122.36482371113298,
                'Seattle',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'long_haul',
                '{"direction": "local", "truck_type": "20T", "available_hours": 41}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '88d15810-4a3a-4812-ab39-fdd664c8fdd3',
                'DRIVER_AVAILABLE',
                'active',
                47.639617442905596,
                -122.35012230769973,
                'Seattle',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'cd86f3a3-7bfb-42ed-8959-858202945a64',
                'DRIVER_AVAILABLE',
                'active',
                47.61385118737285,
                -122.34900958388764,
                'Seattle',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                69,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6b8c37f8-b263-44f9-8b59-281aec6fea15',
                'DRIVER_AVAILABLE',
                'active',
                47.250055542461666,
                -122.41829025967255,
                'Tacoma',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'north',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6c9fd7e1-e9aa-433a-a5b1-e4697cb10235',
                'DRIVER_AVAILABLE',
                'active',
                47.22592321994998,
                -122.41478047076119,
                'Tacoma',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'north',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 14}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '612bdabf-fd4c-461d-947b-f2523e961efe',
                'DRIVER_AVAILABLE',
                'active',
                47.228531599516195,
                -122.45719810828874,
                'Tacoma',
                'United States',
                'Cincinnati',
                'United States',
                39.1031,
                -84.512,
                'north',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                85,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'fd9297ea-0040-4001-9c65-145da05cf9a8',
                'DRIVER_AVAILABLE',
                'active',
                47.27953882556437,
                -122.44650709736604,
                'Tacoma',
                'United States',
                'Omaha',
                'United States',
                41.2565,
                -95.9345,
                'south',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '6111029d-7480-4c22-9dd8-2b8549db8631',
                'DRIVER_AVAILABLE',
                'active',
                47.24755315876866,
                -122.47530277387332,
                'Tacoma',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'south',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'dafa417b-81b1-4e70-acf7-d8a03cd40d1d',
                'DRIVER_AVAILABLE',
                'active',
                47.27127027297047,
                -122.42269199178797,
                'Tacoma',
                'United States',
                'Dallas',
                'United States',
                32.7767,
                -96.797,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 2}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a96bd99e-a58d-4dae-a598-da7f40d65756',
                'DRIVER_AVAILABLE',
                'active',
                47.253135785026544,
                -122.4550319035774,
                'Tacoma',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'long_haul',
                '{"direction": "local", "truck_type": "Van", "available_hours": 30}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                0
            );