INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'fee16571-30b0-4bc5-9acd-a698ba52c527',
                
                'DRIVER_AVAILABLE',
                'active',
                38.60762451965695,
                -90.17311245030434,
                'St. Louis',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'south',
                '{"direction": "east", "truck_type": "20T", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                67,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '735e7747-7e54-44bd-b80f-50f8496f49a5',
                
                'DRIVER_AVAILABLE',
                'active',
                38.61086912052535,
                -90.17787135273919,
                'St. Louis',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'south',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                59,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'be3e28c5-f5da-4101-b0b6-5ce58b116c56',
                
                'DRIVER_AVAILABLE',
                'active',
                38.60062764851353,
                -90.15129903269447,
                'St. Louis',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'local',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 53}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                12,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '19a12fc6-3700-4a28-b0ac-8aebbb429ade',
                
                'DRIVER_AVAILABLE',
                'active',
                38.63707126640988,
                -90.24493537343693,
                'St. Louis',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 40}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                21,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9da408f2-c570-4b05-9efd-aa5ad7a9a6f7',
                
                'DRIVER_AVAILABLE',
                'active',
                38.634988906889646,
                -90.2444252475977,
                'St. Louis',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'south',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                61,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '0d67fd31-1059-451b-8f62-f76b1ae18c87',
                
                'DRIVER_AVAILABLE',
                'active',
                38.612915790328934,
                -90.2169709942969,
                'St. Louis',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'north',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 16}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                41,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b43530b2-10b1-4396-bb14-c1f18e1e1961',
                
                'DRIVER_AVAILABLE',
                'active',
                41.22268991512139,
                -95.92292525859051,
                'Omaha',
                'United States',
                'St. Louis',
                'United States',
                38.627,
                -90.1994,
                'north',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e4653c77-0672-44b9-af1f-d41221cd142d',
                
                'DRIVER_AVAILABLE',
                'active',
                41.274506306833985,
                -95.89534889667836,
                'Omaha',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ddbded9b-24e6-48a1-8f8c-40dca771a621',
                
                'DRIVER_AVAILABLE',
                'active',
                41.29160715013502,
                -95.90925234610333,
                'Omaha',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'north',
                '{"direction": "east", "truck_type": "Van", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '59e1519c-6753-4f79-b14e-67fe7fe1b991',
                
                'DRIVER_AVAILABLE',
                'active',
                41.28843812711188,
                -95.91124505628432,
                'Omaha',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 38}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                78,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e2cf98ec-7141-4623-9cae-c01bda9c00bd',
                
                'DRIVER_AVAILABLE',
                'active',
                41.25157113894125,
                -95.92411490627546,
                'Omaha',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'north',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                81,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '93d7bd55-49f2-4320-bc93-93ac36994d89',
                
                'DRIVER_AVAILABLE',
                'active',
                41.212472804320875,
                -95.89477972028828,
                'Omaha',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'long_haul',
                '{"direction": "east", "truck_type": "20T", "available_hours": 9}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '8c50b9b0-4f12-4734-a340-2f5f95235545',
                
                'DRIVER_AVAILABLE',
                'active',
                41.6107522770638,
                -93.64641813632836,
                'Des Moines',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'local',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9ef63f58-9d6a-4e7f-b60c-e4a8c63f58ff',
                
                'DRIVER_AVAILABLE',
                'active',
                41.5956575289236,
                -93.59936105238957,
                'Des Moines',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9c38fc97-38f4-4db8-92e3-a8eea1896ed1',
                
                'DRIVER_AVAILABLE',
                'active',
                41.54927509959775,
                -93.63931928488137,
                'Des Moines',
                'United States',
                'Indianapolis',
                'United States',
                39.7684,
                -86.1581,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '6398f75a-9378-4e7d-bf93-d38d4e246d0f',
                
                'DRIVER_AVAILABLE',
                'active',
                41.55807104209205,
                -93.57522956873535,
                'Des Moines',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'south',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 52}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9d6dafed-c87f-40b3-94fd-6af087532ee3',
                
                'DRIVER_AVAILABLE',
                'active',
                41.55526559146819,
                -93.58624312933567,
                'Des Moines',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'north',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                62,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '3e6b1b97-ed03-4f65-a4e3-81cdd3d404a2',
                
                'DRIVER_AVAILABLE',
                'active',
                41.559331903893586,
                -93.60928684650554,
                'Des Moines',
                'United States',
                'Salt Lake City',
                'United States',
                40.7608,
                -111.891,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '3ce1dd6a-0a6e-416d-baa2-a15424c05413',
                
                'DRIVER_AVAILABLE',
                'active',
                41.61923895054273,
                -93.65647118172078,
                'Des Moines',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                97,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '08cf3b7c-327f-4ddd-af6f-b04e0a220056',
                
                'DRIVER_AVAILABLE',
                'active',
                41.56557625818049,
                -93.63195602655684,
                'Des Moines',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                77,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '906a8779-bd7c-4adb-9b20-912e12eefef9',
                
                'DRIVER_AVAILABLE',
                'active',
                41.58462312739115,
                -93.63833094762413,
                'Des Moines',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'local',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '655fbd17-43bf-4ebf-bbf6-59e2f2af9b7d',
                
                'DRIVER_AVAILABLE',
                'active',
                41.63084370474848,
                -93.58471670331316,
                'Des Moines',
                'United States',
                'Houston',
                'United States',
                29.7604,
                -95.3698,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                40,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '62d6e19c-0455-401d-ae54-89c6ae8eefc5',
                
                'DRIVER_AVAILABLE',
                'active',
                44.979314838650396,
                -93.26441955663212,
                'Minneapolis',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'south',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                46,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'd2e17292-feb6-40eb-99ed-928269e0188b',
                
                'DRIVER_AVAILABLE',
                'active',
                44.96214706149658,
                -93.3065658052389,
                'Minneapolis',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'north',
                '{"direction": "west", "truck_type": "Van", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b5c8045d-f07e-489e-ac13-0f6d460034ce',
                
                'DRIVER_AVAILABLE',
                'active',
                44.98271655503477,
                -93.29288393346343,
                'Minneapolis',
                'United States',
                'Boston',
                'United States',
                42.3601,
                -71.0589,
                'south',
                '{"direction": "east", "truck_type": "Van", "available_hours": 71}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '1aeb84e9-74bd-4b2f-b2ac-7b151462076b',
                
                'DRIVER_AVAILABLE',
                'active',
                44.98523115727483,
                -93.24049637780745,
                'Minneapolis',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 33}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                92,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'fd37a389-be3c-42c3-8a15-fdb11b2a0f71',
                
                'DRIVER_AVAILABLE',
                'active',
                44.94896237169314,
                -93.2694606316504,
                'Minneapolis',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'south',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                55,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '52834ebc-d57c-47ca-b926-32a6614f18e3',
                
                'DRIVER_AVAILABLE',
                'active',
                44.97240496468806,
                -93.22438346276044,
                'Minneapolis',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                61,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4b1acd29-495b-4e17-aee7-4fef8a87e7c9',
                
                'DRIVER_AVAILABLE',
                'active',
                43.05836663777958,
                -87.89459366423729,
                'Milwaukee',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'long_haul',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'a4972f66-66a8-418d-b20a-71fa2d34f262',
                
                'DRIVER_AVAILABLE',
                'active',
                43.010919217882126,
                -87.9491960817368,
                'Milwaukee',
                'United States',
                'Des Moines',
                'United States',
                41.5868,
                -93.625,
                'long_haul',
                '{"direction": "west", "truck_type": "Van", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                77,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4e4a13d9-1ebc-4481-a765-1ee0724e69d8',
                
                'DRIVER_AVAILABLE',
                'active',
                43.028590967556575,
                -87.88155988181926,
                'Milwaukee',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'south',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 55}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                31,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'd12b7a17-e15a-4128-a562-78f5c29398ea',
                
                'DRIVER_AVAILABLE',
                'active',
                43.027384102245854,
                -87.90140855392171,
                'Milwaukee',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'long_haul',
                '{"direction": "south", "truck_type": "20T", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '0e8a3571-d364-4ce5-9a07-d464e7b18c91',
                
                'DRIVER_AVAILABLE',
                'active',
                43.0732989698835,
                -87.87271328421582,
                'Milwaukee',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'north',
                '{"direction": "west", "truck_type": "Van", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4c23f348-810b-410b-a088-a687ec733eae',
                
                'DRIVER_AVAILABLE',
                'active',
                43.06411203133605,
                -87.91114335549116,
                'Milwaukee',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'local',
                '{"direction": "north", "truck_type": "Van", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '66e2071f-cecd-4437-9168-f1e6b0546a06',
                
                'DRIVER_AVAILABLE',
                'active',
                41.91524631962202,
                -87.62879841848715,
                'Chicago',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'dea456dc-776e-43c8-9e49-edb0c1cea4f1',
                
                'DRIVER_AVAILABLE',
                'active',
                41.87406540555274,
                -87.59424708140001,
                'Chicago',
                'United States',
                'Phoenix',
                'United States',
                33.4484,
                -112.074,
                'long_haul',
                '{"direction": "west", "truck_type": "20T", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                87,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '17766136-5157-465a-aa49-c62790520f6f',
                
                'DRIVER_AVAILABLE',
                'active',
                41.88994231390447,
                -87.60965343832602,
                'Chicago',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'north',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9c20a267-18ba-4652-93bd-23d45c428df2',
                
                'DRIVER_AVAILABLE',
                'active',
                41.92236762218388,
                -87.65772128544874,
                'Chicago',
                'United States',
                'San Antonio',
                'United States',
                29.4241,
                -98.4936,
                'south',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e43fe466-7feb-4361-8105-b43c5c01dc4e',
                
                'DRIVER_AVAILABLE',
                'active',
                41.907354145369794,
                -87.67629240006345,
                'Chicago',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                98,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ffd954f7-01e6-4b06-8b90-e903729b07e6',
                
                'DRIVER_AVAILABLE',
                'active',
                41.9109132564868,
                -87.58581180672984,
                'Chicago',
                'United States',
                'San Antonio',
                'United States',
                29.4241,
                -98.4936,
                'south',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '93716344-44f8-4963-8cea-8cfa2623e527',
                
                'DRIVER_AVAILABLE',
                'active',
                41.90288696269153,
                -87.63034919904545,
                'Chicago',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '939b3665-e2ee-479c-9463-934fd1f8e55f',
                
                'DRIVER_AVAILABLE',
                'active',
                41.891428719375185,
                -87.65112285532156,
                'Chicago',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                13,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c98ca671-ec51-4f09-85a4-5160a84fc05c',
                
                'DRIVER_AVAILABLE',
                'active',
                41.84514540085878,
                -87.62983949161196,
                'Chicago',
                'United States',
                'Jacksonville',
                'United States',
                30.3322,
                -81.6557,
                'south',
                '{"direction": "west", "truck_type": "Van", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ee6a3623-690f-4fdb-b849-ed726f53f2f0',
                
                'DRIVER_AVAILABLE',
                'active',
                39.72143755845086,
                -86.19529554899391,
                'Indianapolis',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'north',
                '{"direction": "local", "truck_type": "Van", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                38,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '8b6b119d-ddc9-4ff1-a50e-66ba0ba885d8',
                
                'DRIVER_AVAILABLE',
                'active',
                39.7605761118669,
                -86.17176645462885,
                'Indianapolis',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'south',
                '{"direction": "east", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '3a765e7d-493f-463b-8a31-946c451fa6ca',
                
                'DRIVER_AVAILABLE',
                'active',
                39.76210693796626,
                -86.18244781421873,
                'Indianapolis',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'south',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '7147d92f-c2f9-4314-ba36-a1cff23657a9',
                
                'DRIVER_AVAILABLE',
                'active',
                39.79683936327103,
                -86.164825919789,
                'Indianapolis',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'cc48f23c-0440-4068-afa2-95e4f5be5c09',
                
                'DRIVER_AVAILABLE',
                'active',
                39.72219780480169,
                -86.15069062662351,
                'Indianapolis',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'local',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                96,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e8a12493-a0b7-4deb-8016-25dfe4a0da55',
                
                'DRIVER_AVAILABLE',
                'active',
                39.75737779387072,
                -86.1872612828604,
                'Indianapolis',
                'United States',
                'Des Moines',
                'United States',
                41.5868,
                -93.625,
                'north',
                '{"direction": "south", "truck_type": "Van", "available_hours": 57}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                25,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b302c75a-b8dc-47c0-bfe3-fc452e0949df',
                
                'DRIVER_AVAILABLE',
                'active',
                42.29417717332753,
                -83.02705199397404,
                'Detroit',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'local',
                '{"direction": "south", "truck_type": "20T", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                2
;
