INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'fee16571-30b0-4bc5-9acd-a698ba52c527',
                
                'DRIVER_AVAILABLE',
                'active',
                36.14607585280435,
                -86.7869082744213,
                'Nashville',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'local',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 21}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                43,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '735e7747-7e54-44bd-b80f-50f8496f49a5',
                
                'DRIVER_AVAILABLE',
                'active',
                35.13814495987069,
                -90.03007202643222,
                'Memphis',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'south',
                '{"direction": "east", "truck_type": "20T", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                67,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'be3e28c5-f5da-4101-b0b6-5ce58b116c56',
                
                'DRIVER_AVAILABLE',
                'active',
                35.171914280686515,
                -90.08518240796276,
                'Memphis',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'north',
                '{"direction": "local", "truck_type": "Van", "available_hours": 38}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                22,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '19a12fc6-3700-4a28-b0ac-8aebbb429ade',
                
                'DRIVER_AVAILABLE',
                'active',
                35.118848950227814,
                -90.02437765532645,
                'Memphis',
                'United States',
                'St. Louis',
                'United States',
                38.627,
                -90.1994,
                'long_haul',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 15}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9da408f2-c570-4b05-9efd-aa5ad7a9a6f7',
                
                'DRIVER_AVAILABLE',
                'active',
                35.131449474675065,
                -90.05940039611097,
                'Memphis',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'local',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 60}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '0d67fd31-1059-451b-8f62-f76b1ae18c87',
                
                'DRIVER_AVAILABLE',
                'active',
                35.14151393696389,
                -90.02682246985859,
                'Memphis',
                'United States',
                'Fort Worth',
                'United States',
                32.7555,
                -97.3308,
                'long_haul',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                56,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b43530b2-10b1-4396-bb14-c1f18e1e1961',
                
                'DRIVER_AVAILABLE',
                'active',
                35.12365867641901,
                -90.05680364121503,
                'Memphis',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'long_haul',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 39}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e4653c77-0672-44b9-af1f-d41221cd142d',
                
                'DRIVER_AVAILABLE',
                'active',
                33.53375795418985,
                -86.79313115952749,
                'Birmingham',
                'United States',
                'Albuquerque',
                'United States',
                35.0844,
                -106.6504,
                'local',
                '{"direction": "east", "truck_type": "20T", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ddbded9b-24e6-48a1-8f8c-40dca771a621',
                
                'DRIVER_AVAILABLE',
                'active',
                33.52381191379883,
                -86.84661415236721,
                'Birmingham',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'local',
                '{"direction": "west", "truck_type": "Van", "available_hours": 58}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                61,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '59e1519c-6753-4f79-b14e-67fe7fe1b991',
                
                'DRIVER_AVAILABLE',
                'active',
                33.53858174648577,
                -86.82046123186315,
                'Birmingham',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e2cf98ec-7141-4623-9cae-c01bda9c00bd',
                
                'DRIVER_AVAILABLE',
                'active',
                33.55058939623567,
                -86.77342929045847,
                'Birmingham',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'north',
                '{"direction": "east", "truck_type": "Van", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '93d7bd55-49f2-4320-bc93-93ac36994d89',
                
                'DRIVER_AVAILABLE',
                'active',
                33.49049874372727,
                -86.82871036193121,
                'Birmingham',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'long_haul',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 41}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                82,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '8c50b9b0-4f12-4734-a340-2f5f95235545',
                
                'DRIVER_AVAILABLE',
                'active',
                33.50542462702912,
                -86.84737058773761,
                'Birmingham',
                'United States',
                'Boston',
                'United States',
                42.3601,
                -71.0589,
                'north',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 35}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                62,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9ef63f58-9d6a-4e7f-b60c-e4a8c63f58ff',
                
                'DRIVER_AVAILABLE',
                'active',
                33.509836733275186,
                -86.7644968844784,
                'Birmingham',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'long_haul',
                '{"direction": "west", "truck_type": "20T", "available_hours": 51}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                95,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9c38fc97-38f4-4db8-92e3-a8eea1896ed1',
                
                'DRIVER_AVAILABLE',
                'active',
                33.55178261430553,
                -86.85865268369855,
                'Birmingham',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 55}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                17,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '6398f75a-9378-4e7d-bf93-d38d4e246d0f',
                
                'DRIVER_AVAILABLE',
                'active',
                33.539621028883616,
                -86.85451210687107,
                'Birmingham',
                'United States',
                'Fort Worth',
                'United States',
                32.7555,
                -97.3308,
                'long_haul',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9d6dafed-c87f-40b3-94fd-6af087532ee3',
                
                'DRIVER_AVAILABLE',
                'active',
                33.52235807866052,
                -86.80838566563001,
                'Birmingham',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                26,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '3e6b1b97-ed03-4f65-a4e3-81cdd3d404a2',
                
                'DRIVER_AVAILABLE',
                'active',
                30.69438002852494,
                -88.05796428343042,
                'Mobile',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'local',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '3ce1dd6a-0a6e-416d-baa2-a15424c05413',
                
                'DRIVER_AVAILABLE',
                'active',
                30.732562913143855,
                -88.00233788921666,
                'Mobile',
                'United States',
                'Salt Lake City',
                'United States',
                40.7608,
                -111.891,
                'south',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                72,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '08cf3b7c-327f-4ddd-af6f-b04e0a220056',
                
                'DRIVER_AVAILABLE',
                'active',
                30.726082153524157,
                -88.02076239812754,
                'Mobile',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '906a8779-bd7c-4adb-9b20-912e12eefef9',
                
                'DRIVER_AVAILABLE',
                'active',
                30.693278800177143,
                -88.05272099660797,
                'Mobile',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'local',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 30}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '655fbd17-43bf-4ebf-bbf6-59e2f2af9b7d',
                
                'DRIVER_AVAILABLE',
                'active',
                30.710513007150197,
                -88.08506632390365,
                'Mobile',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'south',
                '{"direction": "west", "truck_type": "Van", "available_hours": 52}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                98,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '62d6e19c-0455-401d-ae54-89c6ae8eefc5',
                
                'DRIVER_AVAILABLE',
                'active',
                30.687510570692396,
                -88.04143690724288,
                'Mobile',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'south',
                '{"direction": "east", "truck_type": "20T", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                61,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'd2e17292-feb6-40eb-99ed-928269e0188b',
                
                'DRIVER_AVAILABLE',
                'active',
                30.676577076687263,
                -88.03766516269276,
                'Mobile',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'south',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 64}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                7,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b5c8045d-f07e-489e-ac13-0f6d460034ce',
                
                'DRIVER_AVAILABLE',
                'active',
                30.34958910569191,
                -81.65753131449449,
                'Jacksonville',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'north',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 58}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '1aeb84e9-74bd-4b2f-b2ac-7b151462076b',
                
                'DRIVER_AVAILABLE',
                'active',
                30.30068164230206,
                -81.6701214767745,
                'Jacksonville',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'south',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                43,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'fd37a389-be3c-42c3-8a15-fdb11b2a0f71',
                
                'DRIVER_AVAILABLE',
                'active',
                30.344888442788005,
                -81.6658167013033,
                'Jacksonville',
                'United States',
                'Seattle',
                'United States',
                47.6062,
                -122.3321,
                'local',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 47}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                20,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '52834ebc-d57c-47ca-b926-32a6614f18e3',
                
                'DRIVER_AVAILABLE',
                'active',
                30.318431338604622,
                -81.64259503461041,
                'Jacksonville',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'local',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                13,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4b1acd29-495b-4e17-aee7-4fef8a87e7c9',
                
                'DRIVER_AVAILABLE',
                'active',
                30.349858585068187,
                -81.69575718184471,
                'Jacksonville',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'long_haul',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 33}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                19,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'a4972f66-66a8-418d-b20a-71fa2d34f262',
                
                'DRIVER_AVAILABLE',
                'active',
                30.347901689565738,
                -81.70061757057786,
                'Jacksonville',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'local',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 28}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                89,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4e4a13d9-1ebc-4481-a765-1ee0724e69d8',
                
                'DRIVER_AVAILABLE',
                'active',
                30.30759236124505,
                -81.60907540762007,
                'Jacksonville',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'long_haul',
                '{"direction": "west", "truck_type": "Van", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'd12b7a17-e15a-4128-a562-78f5c29398ea',
                
                'DRIVER_AVAILABLE',
                'active',
                30.289599031994573,
                -81.69359366251071,
                'Jacksonville',
                'United States',
                'Minneapolis',
                'United States',
                44.9778,
                -93.265,
                'south',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                26,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '0e8a3571-d364-4ce5-9a07-d464e7b18c91',
                
                'DRIVER_AVAILABLE',
                'active',
                25.75538937287685,
                -80.15364188566862,
                'Miami',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'long_haul',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                97,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4c23f348-810b-410b-a088-a687ec733eae',
                
                'DRIVER_AVAILABLE',
                'active',
                25.763554080766195,
                -80.23165674203287,
                'Miami',
                'United States',
                'Cincinnati',
                'United States',
                39.1031,
                -84.512,
                'south',
                '{"direction": "west", "truck_type": "20T", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '66e2071f-cecd-4437-9168-f1e6b0546a06',
                
                'DRIVER_AVAILABLE',
                'active',
                25.759932149245,
                -80.16140978187661,
                'Miami',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'local',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 37}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                26,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'dea456dc-776e-43c8-9e49-edb0c1cea4f1',
                
                'DRIVER_AVAILABLE',
                'active',
                25.782874213494622,
                -80.15281137009497,
                'Miami',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'south',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 27}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                54,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '17766136-5157-465a-aa49-c62790520f6f',
                
                'DRIVER_AVAILABLE',
                'active',
                25.800674674358177,
                -80.16782654134641,
                'Miami',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'long_haul',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 35}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                66,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9c20a267-18ba-4652-93bd-23d45c428df2',
                
                'DRIVER_AVAILABLE',
                'active',
                27.909918030436437,
                -82.42317418045387,
                'Tampa',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'local',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 6}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                38,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e43fe466-7feb-4361-8105-b43c5c01dc4e',
                
                'DRIVER_AVAILABLE',
                'active',
                27.947448849780773,
                -82.48422464686077,
                'Tampa',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'south',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                74,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ffd954f7-01e6-4b06-8b90-e903729b07e6',
                
                'DRIVER_AVAILABLE',
                'active',
                27.960215139223408,
                -82.41610993830604,
                'Tampa',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'local',
                '{"direction": "west", "truck_type": "Van", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                69,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '93716344-44f8-4963-8cea-8cfa2623e527',
                
                'DRIVER_AVAILABLE',
                'active',
                27.956897180314378,
                -82.4277610841723,
                'Tampa',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 5}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '939b3665-e2ee-479c-9463-934fd1f8e55f',
                
                'DRIVER_AVAILABLE',
                'active',
                27.924297436173525,
                -82.47425360191549,
                'Tampa',
                'United States',
                'Detroit',
                'United States',
                42.3314,
                -83.0458,
                'long_haul',
                '{"direction": "north", "truck_type": "Van", "available_hours": 5}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                60,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c98ca671-ec51-4f09-85a4-5160a84fc05c',
                
                'DRIVER_AVAILABLE',
                'active',
                28.550082449641007,
                -81.36155872728581,
                'Orlando',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'local',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 1}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                98,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ee6a3623-690f-4fdb-b849-ed726f53f2f0',
                
                'DRIVER_AVAILABLE',
                'active',
                28.568119684809595,
                -81.39227201984502,
                'Orlando',
                'United States',
                'Houston',
                'United States',
                29.7604,
                -95.3698,
                'local',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 52}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '8b6b119d-ddc9-4ff1-a50e-66ba0ba885d8',
                
                'DRIVER_AVAILABLE',
                'active',
                28.578746309993786,
                -81.33586917433531,
                'Orlando',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'long_haul',
                '{"direction": "east", "truck_type": "20T", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '3a765e7d-493f-463b-8a31-946c451fa6ca',
                
                'DRIVER_AVAILABLE',
                'active',
                28.530309381473767,
                -81.33634302998328,
                'Orlando',
                'United States',
                'Miami',
                'United States',
                25.7617,
                -80.1918,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 51}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                51,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '7147d92f-c2f9-4314-ba36-a1cff23657a9',
                
                'DRIVER_AVAILABLE',
                'active',
                28.554997452950047,
                -81.36609331900644,
                'Orlando',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'local',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 67}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                58,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'cc48f23c-0440-4068-afa2-95e4f5be5c09',
                
                'DRIVER_AVAILABLE',
                'active',
                28.549035360087487,
                -81.41934448270369,
                'Orlando',
                'United States',
                'Miami',
                'United States',
                25.7617,
                -80.1918,
                'north',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e8a12493-a0b7-4deb-8016-25dfe4a0da55',
                
                'DRIVER_AVAILABLE',
                'active',
                28.550487350859555,
                -81.38315992842259,
                'Orlando',
                'United States',
                'Seattle',
                'United States',
                47.6062,
                -122.3321,
                'north',
                '{"direction": "south", "truck_type": "Van", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                61,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b302c75a-b8dc-47c0-bfe3-fc452e0949df',
                
                'DRIVER_AVAILABLE',
                'active',
                28.560080145496453,
                -81.38016499814061,
                'Orlando',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 57}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                1
;
