INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                38.60762451965695,
                -90.17311245030434,
                'St. Louis',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'south',
                '{"direction": "east", "truck_type": "20T", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                67,
                1
            
            FROM auth.users WHERE email = 'tom.smith22@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                38.61086912052535,
                -90.17787135273919,
                'St. Louis',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'south',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                59,
                5
            
            FROM auth.users WHERE email = 'emma.anderson74@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                38.60062764851353,
                -90.15129903269447,
                'St. Louis',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'local',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 53}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                12,
                3
            
            FROM auth.users WHERE email = 'john.jackson21@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                38.63707126640988,
                -90.24493537343693,
                'St. Louis',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 40}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                21,
                2
            
            FROM auth.users WHERE email = 'tom.doe88@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                38.634988906889646,
                -90.2444252475977,
                'St. Louis',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'south',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                61,
                4
            
            FROM auth.users WHERE email = 'sarah.johnson79@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                38.612915790328934,
                -90.2169709942969,
                'St. Louis',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'north',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 16}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                41,
                0
            
            FROM auth.users WHERE email = 'john.wilson73@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.22268991512139,
                -95.92292525859051,
                'Omaha',
                'United States',
                'St. Louis',
                'United States',
                38.627,
                -90.1994,
                'north',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                4
            
            FROM auth.users WHERE email = 'robert.anderson42@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.274506306833985,
                -95.89534889667836,
                'Omaha',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                1
            
            FROM auth.users WHERE email = 'jane.moore42@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.29160715013502,
                -95.90925234610333,
                'Omaha',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'north',
                '{"direction": "east", "truck_type": "Van", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                2
            
            FROM auth.users WHERE email = 'tom.johnson29@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.28843812711188,
                -95.91124505628432,
                'Omaha',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "east", "truck_type": "Van", "available_hours": 38}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                78,
                5
            
            FROM auth.users WHERE email = 'jane.smith44@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.25157113894125,
                -95.92411490627546,
                'Omaha',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'north',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                81,
                3
            
            FROM auth.users WHERE email = 'david.thomas19@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.212472804320875,
                -95.89477972028828,
                'Omaha',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'long_haul',
                '{"direction": "east", "truck_type": "20T", "available_hours": 9}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                1
            
            FROM auth.users WHERE email = 'jane.wilson82@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.6107522770638,
                -93.64641813632836,
                'Des Moines',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'local',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                4
            
            FROM auth.users WHERE email = 'robert.jackson15@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.5956575289236,
                -93.59936105238957,
                'Des Moines',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                2
            
            FROM auth.users WHERE email = 'lisa.moore29@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.54927509959775,
                -93.63931928488137,
                'Des Moines',
                'United States',
                'Indianapolis',
                'United States',
                39.7684,
                -86.1581,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                1
            
            FROM auth.users WHERE email = 'sarah.taylor72@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.55807104209205,
                -93.57522956873535,
                'Des Moines',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'south',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 52}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                4
            
            FROM auth.users WHERE email = 'emma.thomas71@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.55526559146819,
                -93.58624312933567,
                'Des Moines',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'north',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                62,
                2
            
            FROM auth.users WHERE email = 'mike.taylor61@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.559331903893586,
                -93.60928684650554,
                'Des Moines',
                'United States',
                'Salt Lake City',
                'United States',
                40.7608,
                -111.891,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                5
            
            FROM auth.users WHERE email = 'mike.moore21@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.61923895054273,
                -93.65647118172078,
                'Des Moines',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                97,
                4
            
            FROM auth.users WHERE email = 'jessica.thomas90@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.56557625818049,
                -93.63195602655684,
                'Des Moines',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                77,
                0
            
            FROM auth.users WHERE email = 'tom.jackson24@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.58462312739115,
                -93.63833094762413,
                'Des Moines',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'local',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                3
            
            FROM auth.users WHERE email = 'mike.moore17@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.63084370474848,
                -93.58471670331316,
                'Des Moines',
                'United States',
                'Houston',
                'United States',
                29.7604,
                -95.3698,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                40,
                4
            
            FROM auth.users WHERE email = 'tom.anderson86@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                44.979314838650396,
                -93.26441955663212,
                'Minneapolis',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'south',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                46,
                1
            
            FROM auth.users WHERE email = 'robert.jackson11@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                44.96214706149658,
                -93.3065658052389,
                'Minneapolis',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'north',
                '{"direction": "west", "truck_type": "Van", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                3
            
            FROM auth.users WHERE email = 'jessica.thomas52@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                44.98271655503477,
                -93.29288393346343,
                'Minneapolis',
                'United States',
                'Boston',
                'United States',
                42.3601,
                -71.0589,
                'south',
                '{"direction": "east", "truck_type": "Van", "available_hours": 71}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                5
            
            FROM auth.users WHERE email = 'david.wilson56@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                44.98523115727483,
                -93.24049637780745,
                'Minneapolis',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 33}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                92,
                4
            
            FROM auth.users WHERE email = 'david.moore65@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                44.94896237169314,
                -93.2694606316504,
                'Minneapolis',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'south',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                55,
                3
            
            FROM auth.users WHERE email = 'lisa.taylor40@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                44.97240496468806,
                -93.22438346276044,
                'Minneapolis',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                61,
                0
            
            FROM auth.users WHERE email = 'emma.anderson93@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.05836663777958,
                -87.89459366423729,
                'Milwaukee',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'long_haul',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                3
            
            FROM auth.users WHERE email = 'john.thomas54@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.010919217882126,
                -87.9491960817368,
                'Milwaukee',
                'United States',
                'Des Moines',
                'United States',
                41.5868,
                -93.625,
                'long_haul',
                '{"direction": "west", "truck_type": "Van", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                77,
                2
            
            FROM auth.users WHERE email = 'lisa.jackson64@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.028590967556575,
                -87.88155988181926,
                'Milwaukee',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'south',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 55}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                31,
                4
            
            FROM auth.users WHERE email = 'lisa.doe86@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.027384102245854,
                -87.90140855392171,
                'Milwaukee',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'long_haul',
                '{"direction": "south", "truck_type": "20T", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                4
            
            FROM auth.users WHERE email = 'lisa.johnson50@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.0732989698835,
                -87.87271328421582,
                'Milwaukee',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'north',
                '{"direction": "west", "truck_type": "Van", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                0
            
            FROM auth.users WHERE email = 'lisa.wilson56@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                43.06411203133605,
                -87.91114335549116,
                'Milwaukee',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'local',
                '{"direction": "north", "truck_type": "Van", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                4
            
            FROM auth.users WHERE email = 'john.smith45@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.91524631962202,
                -87.62879841848715,
                'Chicago',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                0
            
            FROM auth.users WHERE email = 'jane.brown70@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.87406540555274,
                -87.59424708140001,
                'Chicago',
                'United States',
                'Phoenix',
                'United States',
                33.4484,
                -112.074,
                'long_haul',
                '{"direction": "west", "truck_type": "20T", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                87,
                1
            
            FROM auth.users WHERE email = 'john.brown43@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.88994231390447,
                -87.60965343832602,
                'Chicago',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'north',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                0
            
            FROM auth.users WHERE email = 'john.taylor40@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.92236762218388,
                -87.65772128544874,
                'Chicago',
                'United States',
                'San Antonio',
                'United States',
                29.4241,
                -98.4936,
                'south',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                5
            
            FROM auth.users WHERE email = 'jessica.brown79@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.907354145369794,
                -87.67629240006345,
                'Chicago',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'long_haul',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                98,
                3
            
            FROM auth.users WHERE email = 'jane.anderson82@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.9109132564868,
                -87.58581180672984,
                'Chicago',
                'United States',
                'San Antonio',
                'United States',
                29.4241,
                -98.4936,
                'south',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                1
            
            FROM auth.users WHERE email = 'tom.doe68@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.90288696269153,
                -87.63034919904545,
                'Chicago',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 8}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                83,
                5
            
            FROM auth.users WHERE email = 'jessica.smith34@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.891428719375185,
                -87.65112285532156,
                'Chicago',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                13,
                1
            
            FROM auth.users WHERE email = 'mike.moore15@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                41.84514540085878,
                -87.62983949161196,
                'Chicago',
                'United States',
                'Jacksonville',
                'United States',
                30.3322,
                -81.6557,
                'south',
                '{"direction": "west", "truck_type": "Van", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                0
            
            FROM auth.users WHERE email = 'david.taylor55@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                39.72143755845086,
                -86.19529554899391,
                'Indianapolis',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'north',
                '{"direction": "local", "truck_type": "Van", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                38,
                4
            
            FROM auth.users WHERE email = 'robert.moore63@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                39.7605761118669,
                -86.17176645462885,
                'Indianapolis',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'south',
                '{"direction": "east", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                27,
                0
            
            FROM auth.users WHERE email = 'john.doe43@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                39.76210693796626,
                -86.18244781421873,
                'Indianapolis',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'south',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                0
            
            FROM auth.users WHERE email = 'emma.taylor51@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                39.79683936327103,
                -86.164825919789,
                'Indianapolis',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                42,
                5
            
            FROM auth.users WHERE email = 'jane.wilson45@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                39.72219780480169,
                -86.15069062662351,
                'Indianapolis',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'local',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                96,
                5
            
            FROM auth.users WHERE email = 'emma.jackson62@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                39.75737779387072,
                -86.1872612828604,
                'Indianapolis',
                'United States',
                'Des Moines',
                'United States',
                41.5868,
                -93.625,
                'north',
                '{"direction": "south", "truck_type": "Van", "available_hours": 57}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                25,
                5
            
            FROM auth.users WHERE email = 'john.jackson31@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                42.29417717332753,
                -83.02705199397404,
                'Detroit',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'local',
                '{"direction": "south", "truck_type": "20T", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                2
            
            FROM auth.users WHERE email = 'jessica.thomas60@example.com';
