INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'fee16571-30b0-4bc5-9acd-a698ba52c527',
                
                'DRIVER_AVAILABLE',
                'active',
                37.84224282250586,
                -122.27337299454908,
                'Oakland',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'long_haul',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 35}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '735e7747-7e54-44bd-b80f-50f8496f49a5',
                
                'DRIVER_AVAILABLE',
                'active',
                37.800450072685095,
                -122.31991603087891,
                'Oakland',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'north',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 70}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'be3e28c5-f5da-4101-b0b6-5ce58b116c56',
                
                'DRIVER_AVAILABLE',
                'active',
                37.760159970212605,
                -122.23478369215103,
                'Oakland',
                'United States',
                'Indianapolis',
                'United States',
                39.7684,
                -86.1581,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '19a12fc6-3700-4a28-b0ac-8aebbb429ade',
                
                'DRIVER_AVAILABLE',
                'active',
                37.76793367354941,
                -122.31442522252813,
                'Oakland',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'north',
                '{"direction": "local", "truck_type": "20T", "available_hours": 15}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9da408f2-c570-4b05-9efd-aa5ad7a9a6f7',
                
                'DRIVER_AVAILABLE',
                'active',
                37.82272596612802,
                -122.25974312459779,
                'Oakland',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'north',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 45}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                79,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '0d67fd31-1059-451b-8f62-f76b1ae18c87',
                
                'DRIVER_AVAILABLE',
                'active',
                37.776201855426834,
                -122.26183559944825,
                'Oakland',
                'United States',
                'Minneapolis',
                'United States',
                44.9778,
                -93.265,
                'south',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                68,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b43530b2-10b1-4396-bb14-c1f18e1e1961',
                
                'DRIVER_AVAILABLE',
                'active',
                37.76000152406873,
                -122.22643805236893,
                'Oakland',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'north',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 47}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                58,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e4653c77-0672-44b9-af1f-d41221cd142d',
                
                'DRIVER_AVAILABLE',
                'active',
                37.84595278447686,
                -122.31945490069259,
                'Oakland',
                'United States',
                'Fort Worth',
                'United States',
                32.7555,
                -97.3308,
                'south',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                50,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ddbded9b-24e6-48a1-8f8c-40dca771a621',
                
                'DRIVER_AVAILABLE',
                'active',
                37.80457288734226,
                -122.25053852753658,
                'Oakland',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'long_haul',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 1}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                46,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '59e1519c-6753-4f79-b14e-67fe7fe1b991',
                
                'DRIVER_AVAILABLE',
                'active',
                37.76102911567019,
                -122.29291515801856,
                'Oakland',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'local',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 47}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e2cf98ec-7141-4623-9cae-c01bda9c00bd',
                
                'DRIVER_AVAILABLE',
                'active',
                37.36561064921601,
                -121.90908903561689,
                'San Jose',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'north',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 1}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                19,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '93d7bd55-49f2-4320-bc93-93ac36994d89',
                
                'DRIVER_AVAILABLE',
                'active',
                37.37024555769256,
                -121.86116597665648,
                'San Jose',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'north',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                41,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '8c50b9b0-4f12-4734-a340-2f5f95235545',
                
                'DRIVER_AVAILABLE',
                'active',
                37.2897546905678,
                -121.9103577434885,
                'San Jose',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'north',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9ef63f58-9d6a-4e7f-b60c-e4a8c63f58ff',
                
                'DRIVER_AVAILABLE',
                'active',
                37.30408232741708,
                -121.91325058759755,
                'San Jose',
                'United States',
                'Miami',
                'United States',
                25.7617,
                -80.1918,
                'north',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 40}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                63,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9c38fc97-38f4-4db8-92e3-a8eea1896ed1',
                
                'DRIVER_AVAILABLE',
                'active',
                37.31359120042885,
                -121.83912533002488,
                'San Jose',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'local',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 3}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                84,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '6398f75a-9378-4e7d-bf93-d38d4e246d0f',
                
                'DRIVER_AVAILABLE',
                'active',
                37.3400025784687,
                -121.86110686724194,
                'San Jose',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                76,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9d6dafed-c87f-40b3-94fd-6af087532ee3',
                
                'DRIVER_AVAILABLE',
                'active',
                38.58168905811601,
                -121.46566032001633,
                'Sacramento',
                'United States',
                'Minneapolis',
                'United States',
                44.9778,
                -93.265,
                'local',
                '{"direction": "local", "truck_type": "Van", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '3e6b1b97-ed03-4f65-a4e3-81cdd3d404a2',
                
                'DRIVER_AVAILABLE',
                'active',
                38.611219076660845,
                -121.51131760341885,
                'Sacramento',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'local',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                54,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '3ce1dd6a-0a6e-416d-baa2-a15424c05413',
                
                'DRIVER_AVAILABLE',
                'active',
                38.566178244424286,
                -121.4721177897306,
                'Sacramento',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'local',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                99,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '08cf3b7c-327f-4ddd-af6f-b04e0a220056',
                
                'DRIVER_AVAILABLE',
                'active',
                38.55608336211991,
                -121.50446772600145,
                'Sacramento',
                'United States',
                'San Francisco',
                'United States',
                37.7749,
                -122.4194,
                'local',
                '{"direction": "east", "truck_type": "20T", "available_hours": 14}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                73,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '906a8779-bd7c-4adb-9b20-912e12eefef9',
                
                'DRIVER_AVAILABLE',
                'active',
                38.5915628487742,
                -121.5245397471839,
                'Sacramento',
                'United States',
                'Columbus',
                'United States',
                39.9612,
                -82.9988,
                'south',
                '{"direction": "north", "truck_type": "20T", "available_hours": 56}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '655fbd17-43bf-4ebf-bbf6-59e2f2af9b7d',
                
                'DRIVER_AVAILABLE',
                'active',
                38.62652830671273,
                -121.52290439072662,
                'Sacramento',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'north',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                39,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '62d6e19c-0455-401d-ae54-89c6ae8eefc5',
                
                'DRIVER_AVAILABLE',
                'active',
                38.590454817687494,
                -121.49726453049085,
                'Sacramento',
                'United States',
                'Washington',
                'United States',
                38.9072,
                -77.0369,
                'long_haul',
                '{"direction": "west", "truck_type": "Van", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'd2e17292-feb6-40eb-99ed-928269e0188b',
                
                'DRIVER_AVAILABLE',
                'active',
                37.9406550617454,
                -121.25741291534689,
                'Stockton',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'long_haul',
                '{"direction": "east", "truck_type": "Van", "available_hours": 33}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                98,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b5c8045d-f07e-489e-ac13-0f6d460034ce',
                
                'DRIVER_AVAILABLE',
                'active',
                37.9173972849357,
                -121.27946734469835,
                'Stockton',
                'United States',
                'Boston',
                'United States',
                42.3601,
                -71.0589,
                'long_haul',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 51}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                84,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '1aeb84e9-74bd-4b2f-b2ac-7b151462076b',
                
                'DRIVER_AVAILABLE',
                'active',
                37.914946587356404,
                -121.29627020440006,
                'Stockton',
                'United States',
                'Otay Mesa',
                'United States',
                32.571,
                -116.9716,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 7}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                51,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'fd37a389-be3c-42c3-8a15-fdb11b2a0f71',
                
                'DRIVER_AVAILABLE',
                'active',
                37.90925356994569,
                -121.27040401513885,
                'Stockton',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'north',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 39}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                70,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '52834ebc-d57c-47ca-b926-32a6614f18e3',
                
                'DRIVER_AVAILABLE',
                'active',
                37.9807117941577,
                -121.26643271760247,
                'Stockton',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'local',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 35}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                30,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4b1acd29-495b-4e17-aee7-4fef8a87e7c9',
                
                'DRIVER_AVAILABLE',
                'active',
                37.678203152495335,
                -121.0077556985709,
                'Modesto',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'north',
                '{"direction": "south", "truck_type": "20T", "available_hours": 6}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'a4972f66-66a8-418d-b20a-71fa2d34f262',
                
                'DRIVER_AVAILABLE',
                'active',
                37.638341867383,
                -121.00157647431286,
                'Modesto',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4e4a13d9-1ebc-4481-a765-1ee0724e69d8',
                
                'DRIVER_AVAILABLE',
                'active',
                37.631432584871504,
                -120.99404161144123,
                'Modesto',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'south',
                '{"direction": "local", "truck_type": "20T", "available_hours": 6}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                78,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'd12b7a17-e15a-4128-a562-78f5c29398ea',
                
                'DRIVER_AVAILABLE',
                'active',
                37.65391353024819,
                -121.02065461047803,
                'Modesto',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'local',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                41,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '0e8a3571-d364-4ce5-9a07-d464e7b18c91',
                
                'DRIVER_AVAILABLE',
                'active',
                37.64843531525414,
                -120.98543195843892,
                'Modesto',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'north',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                60,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '4c23f348-810b-410b-a088-a687ec733eae',
                
                'DRIVER_AVAILABLE',
                'active',
                37.64033473480423,
                -121.02775924308564,
                'Modesto',
                'United States',
                'Cleveland',
                'United States',
                41.4993,
                -81.6944,
                'long_haul',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 53}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                47,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '66e2071f-cecd-4437-9168-f1e6b0546a06',
                
                'DRIVER_AVAILABLE',
                'active',
                36.72284113596735,
                -119.79212719229373,
                'Fresno',
                'United States',
                'Boston',
                'United States',
                42.3601,
                -71.0589,
                'north',
                '{"direction": "north", "truck_type": "20T", "available_hours": 15}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                40,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'dea456dc-776e-43c8-9e49-edb0c1cea4f1',
                
                'DRIVER_AVAILABLE',
                'active',
                36.78524776209695,
                -119.74843543236182,
                'Fresno',
                'United States',
                'Modesto',
                'United States',
                37.6391,
                -120.9969,
                'north',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 2}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '17766136-5157-465a-aa49-c62790520f6f',
                
                'DRIVER_AVAILABLE',
                'active',
                36.73759228043423,
                -119.81196832934562,
                'Fresno',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'north',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                8,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '9c20a267-18ba-4652-93bd-23d45c428df2',
                
                'DRIVER_AVAILABLE',
                'active',
                36.77953431830012,
                -119.77193350839724,
                'Fresno',
                'United States',
                'Houston',
                'United States',
                29.7604,
                -95.3698,
                'north',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                13,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e43fe466-7feb-4361-8105-b43c5c01dc4e',
                
                'DRIVER_AVAILABLE',
                'active',
                36.697631005513905,
                -119.8148263340293,
                'Fresno',
                'United States',
                'Dallas',
                'United States',
                32.7767,
                -96.797,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 27}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                57,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ffd954f7-01e6-4b06-8b90-e903729b07e6',
                
                'DRIVER_AVAILABLE',
                'active',
                36.70360695139042,
                -119.74152689437449,
                'Fresno',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'local',
                '{"direction": "west", "truck_type": "Van", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '93716344-44f8-4963-8cea-8cfa2623e527',
                
                'DRIVER_AVAILABLE',
                'active',
                36.70899547353853,
                -119.81728295435656,
                'Fresno',
                'United States',
                'Kansas City',
                'United States',
                39.0997,
                -94.5786,
                'long_haul',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                82,
                3
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '939b3665-e2ee-479c-9463-934fd1f8e55f',
                
                'DRIVER_AVAILABLE',
                'active',
                35.37234457119745,
                -119.05155202442724,
                'Bakersfield',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'north',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 28}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                64,
                5
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'c98ca671-ec51-4f09-85a4-5160a84fc05c',
                
                'DRIVER_AVAILABLE',
                'active',
                35.40558345573387,
                -119.06554100793632,
                'Bakersfield',
                'United States',
                'Albuquerque',
                'United States',
                35.0844,
                -106.6504,
                'south',
                '{"direction": "north", "truck_type": "Flatbed", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                16,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'ee6a3623-690f-4fdb-b849-ed726f53f2f0',
                
                'DRIVER_AVAILABLE',
                'active',
                35.39698072499215,
                -118.99983627978816,
                'Bakersfield',
                'United States',
                'Indianapolis',
                'United States',
                39.7684,
                -86.1581,
                'local',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 14}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                76,
                0
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '8b6b119d-ddc9-4ff1-a50e-66ba0ba885d8',
                
                'DRIVER_AVAILABLE',
                'active',
                35.33053044509168,
                -118.9870966782455,
                'Bakersfield',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                6,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '3a765e7d-493f-463b-8a31-946c451fa6ca',
                
                'DRIVER_AVAILABLE',
                'active',
                35.34059410969772,
                -119.03031663180103,
                'Bakersfield',
                'United States',
                'Oklahoma City',
                'United States',
                35.4676,
                -97.5164,
                'local',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 60}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                '7147d92f-c2f9-4314-ba36-a1cff23657a9',
                
                'DRIVER_AVAILABLE',
                'active',
                35.348228347749185,
                -119.02545590725383,
                'Bakersfield',
                'United States',
                'Minneapolis',
                'United States',
                44.9778,
                -93.265,
                'local',
                '{"direction": "west", "truck_type": "Van", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                86,
                1
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'cc48f23c-0440-4068-afa2-95e4f5be5c09',
                
                'DRIVER_AVAILABLE',
                'active',
                35.325623773943576,
                -118.98481278003132,
                'Bakersfield',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'north',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                79,
                4
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'e8a12493-a0b7-4deb-8016-25dfe4a0da55',
                
                'DRIVER_AVAILABLE',
                'active',
                35.363496806691224,
                -119.03369398434704,
                'Bakersfield',
                'United States',
                'El Paso',
                'United States',
                31.7619,
                -106.485,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 72}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                89,
                2
;
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                'b302c75a-b8dc-47c0-bfe3-fc452e0949df',
                
                'DRIVER_AVAILABLE',
                'active',
                35.39204635845123,
                -118.99919913715026,
                'Bakersfield',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'local',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                50,
                3
;
