INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '540a33d5-d726-46c0-a14a-2b39a9e0f57c',
                'DRIVER_AVAILABLE',
                'active',
                42.34530632726915,
                -83.00321242352031,
                'Detroit',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'south',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                5,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'caa322a3-2f50-4706-838d-8ddf9d077d4f',
                'DRIVER_AVAILABLE',
                'active',
                42.286893178542165,
                -83.00129690211082,
                'Detroit',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'south',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 9}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                76,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'c74cbd62-8683-4686-91d2-88a98d3370db',
                'DRIVER_AVAILABLE',
                'active',
                42.283246746806284,
                -82.99882260142898,
                'Detroit',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'local',
                '{"direction": "east", "truck_type": "20T", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'd6053533-1ea7-4e90-9864-c7df0ea566ec',
                'DRIVER_AVAILABLE',
                'active',
                42.2935060623319,
                -83.08853252387418,
                'Detroit',
                'United States',
                'Indianapolis',
                'United States',
                39.7684,
                -86.1581,
                'local',
                '{"direction": "local", "truck_type": "20T", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                45,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '5a03f580-dfd1-488d-8b09-df887de139f9',
                'DRIVER_AVAILABLE',
                'active',
                42.311117965175654,
                -83.03492119123692,
                'Detroit',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'north',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 28}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                56,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'dcef5bb6-ec4e-4990-9be0-6cd05ca4f9d3',
                'DRIVER_AVAILABLE',
                'active',
                39.99491633730407,
                -82.97430540992222,
                'Columbus',
                'United States',
                'Memphis',
                'United States',
                35.1495,
                -90.049,
                'long_haul',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                51,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '7ec55f1a-fdb1-4c7c-9be1-bf143a908cb7',
                'DRIVER_AVAILABLE',
                'active',
                40.00110936311273,
                -83.03888578804654,
                'Columbus',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'north',
                '{"direction": "local", "truck_type": "Van", "available_hours": 25}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                78,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '96a1e7ec-79f9-437b-8d8c-e465f4c0e9ee',
                'DRIVER_AVAILABLE',
                'active',
                39.9223712577467,
                -82.99697569135618,
                'Columbus',
                'United States',
                'Laredo',
                'United States',
                27.5306,
                -99.4803,
                'south',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 70}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                70,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4a48d287-d459-4fb2-a54c-80be2445cec9',
                'DRIVER_AVAILABLE',
                'active',
                39.91319011679585,
                -82.95076258632348,
                'Columbus',
                'United States',
                'Fresno',
                'United States',
                36.7378,
                -119.7871,
                'long_haul',
                '{"direction": "local", "truck_type": "Flatbed", "available_hours": 51}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                25,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'df2c94a6-f1e9-456f-a3b7-432804372d2a',
                'DRIVER_AVAILABLE',
                'active',
                39.958421709288274,
                -82.97961651464841,
                'Columbus',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'north',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 15}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                31,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '1ba6b755-b70e-4b92-a1f5-4cccc4930c5a',
                'DRIVER_AVAILABLE',
                'active',
                39.92247679197921,
                -83.01161406827474,
                'Columbus',
                'United States',
                'Salt Lake City',
                'United States',
                40.7608,
                -111.891,
                'local',
                '{"direction": "west", "truck_type": "20T", "available_hours": 28}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                70,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a7c26015-8d12-4246-a83d-603d89d3e5fa',
                'DRIVER_AVAILABLE',
                'active',
                39.96054963520325,
                -82.97729948307806,
                'Columbus',
                'United States',
                'Oakland',
                'United States',
                37.8044,
                -122.2711,
                'south',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '3a79532d-a36e-4628-99f9-b59b5a9d204f',
                'DRIVER_AVAILABLE',
                'active',
                40.0063760297726,
                -83.0151115027292,
                'Columbus',
                'United States',
                'Dallas',
                'United States',
                32.7767,
                -96.797,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 55}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                81,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'be56709d-59c5-49de-ac64-ac7dc5c8f5c3',
                'DRIVER_AVAILABLE',
                'active',
                39.9255105473676,
                -83.03216498659157,
                'Columbus',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'south',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                52,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'a302ca93-0db7-4ce7-8c12-3f6da7c037c7',
                'DRIVER_AVAILABLE',
                'active',
                41.498734223623444,
                -81.66652125102036,
                'Cleveland',
                'United States',
                'Fresno',
                'United States',
                36.7378,
                -119.7871,
                'long_haul',
                '{"direction": "local", "truck_type": "Van", "available_hours": 9}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                46,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '12d64e7c-c819-4f50-aca0-47fcb02e7ecb',
                'DRIVER_AVAILABLE',
                'active',
                41.451809832834606,
                -81.64534430932932,
                'Cleveland',
                'United States',
                'Fresno',
                'United States',
                36.7378,
                -119.7871,
                'north',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 37}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                10,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'dd58e3d4-6405-43b8-8b39-9577966a2535',
                'DRIVER_AVAILABLE',
                'active',
                41.49901885566507,
                -81.67172364862684,
                'Cleveland',
                'United States',
                'Albuquerque',
                'United States',
                35.0844,
                -106.6504,
                'local',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                53,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0ae772f2-734e-4a3a-b4fa-b92ac494ff08',
                'DRIVER_AVAILABLE',
                'active',
                41.51132999647096,
                -81.67171563518963,
                'Cleveland',
                'United States',
                'Miami',
                'United States',
                25.7617,
                -80.1918,
                'south',
                '{"direction": "north", "truck_type": "Van", "available_hours": 39}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                23,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '7c450fc1-7355-487c-9159-8a94be39dc59',
                'DRIVER_AVAILABLE',
                'active',
                41.515225517714455,
                -81.67100317024916,
                'Cleveland',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'south',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 30}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                71,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '68d19801-6160-42e6-bb34-52c317d40651',
                'DRIVER_AVAILABLE',
                'active',
                41.5062997836044,
                -81.6991859131771,
                'Cleveland',
                'United States',
                'Oklahoma City',
                'United States',
                35.4676,
                -97.5164,
                'south',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                85,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '9c368d32-6a23-4759-9a88-5ef778e08562',
                'DRIVER_AVAILABLE',
                'active',
                41.475889392382975,
                -81.73212418825082,
                'Cleveland',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'north',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 53}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                21,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '28067147-7a1f-42a0-88ef-9faef69de436',
                'DRIVER_AVAILABLE',
                'active',
                39.14093601841295,
                -84.49912355356636,
                'Cincinnati',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'local',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                69,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ea7a74b4-c80b-41a0-844a-a8793553f601',
                'DRIVER_AVAILABLE',
                'active',
                39.09605045048314,
                -84.4838381767075,
                'Cincinnati',
                'United States',
                'Mobile',
                'United States',
                30.6954,
                -88.0399,
                'long_haul',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 68}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                32,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '9146cf67-18bf-466d-b9d1-415205018818',
                'DRIVER_AVAILABLE',
                'active',
                39.13743737610649,
                -84.46472319584636,
                'Cincinnati',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'south',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 41}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                62,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '0fe38613-0873-471d-b48d-79da3ad97529',
                'DRIVER_AVAILABLE',
                'active',
                39.11292006025542,
                -84.55457141167825,
                'Cincinnati',
                'United States',
                'Phoenix',
                'United States',
                33.4484,
                -112.074,
                'south',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 42}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                51,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '19eba798-4d2e-49e6-88f5-5072a2d4acbd',
                'DRIVER_AVAILABLE',
                'active',
                39.08547727451459,
                -84.52914349969896,
                'Cincinnati',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'south',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 30}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                64,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'b5a8d388-0831-4129-824a-2cac973d6ed3',
                'DRIVER_AVAILABLE',
                'active',
                39.075900684735345,
                -84.4972673089483,
                'Cincinnati',
                'United States',
                'Los Angeles',
                'United States',
                34.0522,
                -118.2437,
                'north',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4d64c452-379c-498e-9c6a-0f3942a659c1',
                'DRIVER_AVAILABLE',
                'active',
                39.05851195308603,
                -84.53001553680035,
                'Cincinnati',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                34,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'b25e0728-ace5-45ad-aaa8-68b2089bdf18',
                'DRIVER_AVAILABLE',
                'active',
                33.7132086958865,
                -84.40872212917033,
                'Atlanta',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'south',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 29}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                60,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '05c3a4fd-8877-44a2-bdbe-cd42e2be8d39',
                'DRIVER_AVAILABLE',
                'active',
                33.774591569765555,
                -84.3858567846713,
                'Atlanta',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'long_haul',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                30,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'ccd13c71-bd6b-4820-819d-7bfea8ee0687',
                'DRIVER_AVAILABLE',
                'active',
                33.72826956814245,
                -84.37738324525625,
                'Atlanta',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'local',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 64}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                62,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'e7d4a560-1d55-4ee7-b5c2-aebc0d520359',
                'DRIVER_AVAILABLE',
                'active',
                33.76462593146837,
                -84.3594374716537,
                'Atlanta',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'north',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 38}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                24,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'bad20e60-712c-4220-aaeb-e252eaed1be8',
                'DRIVER_AVAILABLE',
                'active',
                33.70079543324285,
                -84.39589315437405,
                'Atlanta',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'south',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                0,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '55b45593-afb4-4a74-96dc-f71193c3f9e1',
                'DRIVER_AVAILABLE',
                'active',
                33.74512172446064,
                -84.34715827530837,
                'Atlanta',
                'United States',
                'Ontario',
                'United States',
                34.0633,
                -117.6509,
                'local',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 15}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                36,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '3010eab3-24fc-4f6a-a902-2c4ced70e2ef',
                'DRIVER_AVAILABLE',
                'active',
                33.71660771098629,
                -84.35829854318847,
                'Atlanta',
                'United States',
                'Stockton',
                'United States',
                37.9577,
                -121.2908,
                'south',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 47}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                3,
                4
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'd4c7302a-6f10-4fa4-9925-6c77fa7b1495',
                'DRIVER_AVAILABLE',
                'active',
                33.764878002383874,
                -84.38293783921387,
                'Atlanta',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'long_haul',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 41}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                94,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '89b6d555-62fe-4808-abba-1f3c607a96e9',
                'DRIVER_AVAILABLE',
                'active',
                33.70923981240894,
                -84.39596398379025,
                'Atlanta',
                'United States',
                'Detroit',
                'United States',
                42.3314,
                -83.0458,
                'long_haul',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                58,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '47b48c7d-cdda-42dd-a485-fdaae610a212',
                'DRIVER_AVAILABLE',
                'active',
                33.7897202316012,
                -84.3668967165101,
                'Atlanta',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'north',
                '{"direction": "west", "truck_type": "Box Truck", "available_hours": 34}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                58,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '97184c1e-0f7c-418d-835d-569dc190232b',
                'DRIVER_AVAILABLE',
                'active',
                35.19095968829799,
                -80.89173710754191,
                'Charlotte',
                'United States',
                'Houston',
                'United States',
                29.7604,
                -95.3698,
                'south',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 23}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '447b0d47-146e-43ac-a2bf-a4ce4460199d',
                'DRIVER_AVAILABLE',
                'active',
                35.25637295381539,
                -80.81420817212441,
                'Charlotte',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'south',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 28}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                85,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '67164c02-aa36-4063-8897-3c6a7a29a339',
                'DRIVER_AVAILABLE',
                'active',
                35.244602849225416,
                -80.79913437614812,
                'Charlotte',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'long_haul',
                '{"direction": "west", "truck_type": "Refrigerated", "available_hours": 70}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                6,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '34da26d9-c5a7-473e-9844-3cf6a6b3b2cc',
                'DRIVER_AVAILABLE',
                'active',
                35.24390785719617,
                -80.87632238755191,
                'Charlotte',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'long_haul',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 52}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                64,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '511e61e6-4240-427c-8695-65d558785321',
                'DRIVER_AVAILABLE',
                'active',
                35.27537604575905,
                -80.81169209553563,
                'Charlotte',
                'United States',
                'Des Moines',
                'United States',
                41.5868,
                -93.625,
                'north',
                '{"direction": "south", "truck_type": "Van", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                60,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '903a7045-f6b2-4a51-bb48-0ec91635b6fd',
                'DRIVER_AVAILABLE',
                'active',
                35.178877599299824,
                -80.88079914966491,
                'Charlotte',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'long_haul',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 24}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                1,
                5
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '98245e11-d390-40af-8dd2-452010baf028',
                'DRIVER_AVAILABLE',
                'active',
                35.193388019389076,
                -80.82914774460431,
                'Charlotte',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                35,
                3
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '170c6111-14fb-4457-90d2-a193d4700a64',
                'DRIVER_AVAILABLE',
                'active',
                35.18737119803808,
                -80.84953905034934,
                'Charlotte',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 14}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                89,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '5af5bee1-c52f-461c-824b-40b0ee548dc9',
                'DRIVER_AVAILABLE',
                'active',
                36.11708790053374,
                -86.83045820657688,
                'Nashville',
                'United States',
                'Charlotte',
                'United States',
                35.2271,
                -80.8431,
                'north',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                93,
                1
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                'f564485b-0e45-45f1-b386-4552aedef5a7',
                'DRIVER_AVAILABLE',
                'active',
                36.11373990013483,
                -86.81550418693858,
                'Nashville',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'north',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                0
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '8b6a1fcc-d98a-466d-a975-68dba5b960c0',
                'DRIVER_AVAILABLE',
                'active',
                36.12248810192697,
                -86.74420981259958,
                'Nashville',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'north',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                87,
                2
            );
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            ) VALUES (
                gen_random_uuid(),
                '4861572d-aa95-4fdf-a5ef-9478212f0bbd',
                'DRIVER_AVAILABLE',
                'active',
                36.15856263857654,
                -86.73524356812288,
                'Nashville',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'local',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                45,
                4
            );