INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.02782358315851,
                -118.26171901241175,
                'Los Angeles',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'long_haul',
                '{"direction": "local", "truck_type": "Van", "available_hours": 56}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                2
            
            FROM auth.users WHERE email = 'lisa.brown75@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.08485972308629,
                -118.22761428667239,
                'Los Angeles',
                'United States',
                'Orlando',
                'United States',
                28.5383,
                -81.3792,
                'north',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 10}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                17,
                2
            
            FROM auth.users WHERE email = 'emma.wilson97@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.0756052452517,
                -118.28041505179013,
                'Los Angeles',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'long_haul',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                71,
                2
            
            FROM auth.users WHERE email = 'robert.taylor86@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.00260664351825,
                -118.24397943089537,
                'Los Angeles',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'south',
                '{"direction": "local", "truck_type": "Van", "available_hours": 20}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                49,
                5
            
            FROM auth.users WHERE email = 'john.thomas94@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.029172413475216,
                -118.22802750753876,
                'Los Angeles',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'local',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 65}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                5
            
            FROM auth.users WHERE email = 'robert.wilson90@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.09430775564912,
                -118.27437530045734,
                'Los Angeles',
                'United States',
                'San Antonio',
                'United States',
                29.4241,
                -98.4936,
                'north',
                '{"direction": "south", "truck_type": "20T", "available_hours": 54}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                48,
                4
            
            FROM auth.users WHERE email = 'robert.smith65@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.09261705206108,
                -118.28574986259035,
                'Los Angeles',
                'United States',
                'Boise',
                'United States',
                43.615,
                -116.2023,
                'local',
                '{"direction": "local", "truck_type": "Refrigerated", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                14,
                1
            
            FROM auth.users WHERE email = 'mike.brown99@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.10066564640849,
                -118.2165657682745,
                'Los Angeles',
                'United States',
                'Stockton',
                'United States',
                37.9577,
                -121.2908,
                'south',
                '{"direction": "west", "truck_type": "20T", "available_hours": 32}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                11,
                2
            
            FROM auth.users WHERE email = 'mike.jackson60@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.02904365225925,
                -118.27656673313821,
                'Los Angeles',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'local',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 43}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                100,
                5
            
            FROM auth.users WHERE email = 'robert.johnson63@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.743779520428966,
                -118.21303558974436,
                'Long Beach',
                'United States',
                'Minneapolis',
                'United States',
                44.9778,
                -93.265,
                'local',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 39}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                5
            
            FROM auth.users WHERE email = 'jane.wilson58@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.74711854088399,
                -118.19103632794244,
                'Long Beach',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'north',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 48}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                87,
                0
            
            FROM auth.users WHERE email = 'david.johnson44@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.81975493537257,
                -118.21679127529771,
                'Long Beach',
                'United States',
                'Tacoma',
                'United States',
                47.2529,
                -122.4443,
                'local',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 60}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                1
            
            FROM auth.users WHERE email = 'david.wilson47@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.782167250497565,
                -118.15803405915422,
                'Long Beach',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'north',
                '{"direction": "east", "truck_type": "Flatbed", "available_hours": 6}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                3
            
            FROM auth.users WHERE email = 'tom.taylor84@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.74409058121284,
                -118.21615350650706,
                'Long Beach',
                'United States',
                'Nashville',
                'United States',
                36.1627,
                -86.7816,
                'long_haul',
                '{"direction": "east", "truck_type": "Van", "available_hours": 46}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                50,
                3
            
            FROM auth.users WHERE email = 'tom.brown15@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.8198896371281,
                -118.1575013366271,
                'Long Beach',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'local',
                '{"direction": "east", "truck_type": "20T", "available_hours": 22}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                65,
                1
            
            FROM auth.users WHERE email = 'jessica.brown67@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.72991933820335,
                -118.1868293833216,
                'Long Beach',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'north',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                29,
                0
            
            FROM auth.users WHERE email = 'tom.doe38@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.72902590349185,
                -118.15698994254984,
                'Long Beach',
                'United States',
                'Tulsa',
                'United States',
                36.1539,
                -95.9928,
                'local',
                '{"direction": "west", "truck_type": "Van", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                62,
                2
            
            FROM auth.users WHERE email = 'robert.anderson59@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.78104250768177,
                -118.24137626399917,
                'Long Beach',
                'United States',
                'Albuquerque',
                'United States',
                35.0844,
                -106.6504,
                'south',
                '{"direction": "north", "truck_type": "Van", "available_hours": 69}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                8,
                4
            
            FROM auth.users WHERE email = 'mike.jackson30@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                33.782523257710054,
                -118.186737216404,
                'Long Beach',
                'United States',
                'Pittsburgh',
                'United States',
                40.4406,
                -79.9959,
                'local',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                97,
                3
            
            FROM auth.users WHERE email = 'jane.smith66@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.08942006413813,
                -117.69357372641845,
                'Ontario',
                'United States',
                'Tampa',
                'United States',
                27.9506,
                -82.4572,
                'local',
                '{"direction": "west", "truck_type": "Flatbed", "available_hours": 51}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                56,
                0
            
            FROM auth.users WHERE email = 'john.thomas14@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.08105531963416,
                -117.61595867137336,
                'Ontario',
                'United States',
                'Bakersfield',
                'United States',
                35.3733,
                -119.0187,
                'long_haul',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                52,
                2
            
            FROM auth.users WHERE email = 'emma.moore68@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.07178073460132,
                -117.6254771982352,
                'Ontario',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'north',
                '{"direction": "west", "truck_type": "20T", "available_hours": 12}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                1
            
            FROM auth.users WHERE email = 'john.taylor13@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.04815949519135,
                -117.65130022215583,
                'Ontario',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'south',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 55}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                67,
                5
            
            FROM auth.users WHERE email = 'lisa.doe91@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.09599497761205,
                -117.61232545237247,
                'Ontario',
                'United States',
                'San Antonio',
                'United States',
                29.4241,
                -98.4936,
                'south',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 49}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                5,
                4
            
            FROM auth.users WHERE email = 'emma.doe89@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.09922598568261,
                -117.69885175113602,
                'Ontario',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 61}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                60,
                3
            
            FROM auth.users WHERE email = 'robert.brown80@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                34.014289960612345,
                -117.66782760125687,
                'Ontario',
                'United States',
                'Birmingham',
                'United States',
                33.5186,
                -86.8104,
                'long_haul',
                '{"direction": "north", "truck_type": "20T", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                0
            
            FROM auth.users WHERE email = 'tom.thomas52@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.75260830551222,
                -117.20784828408516,
                'San Diego',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'local',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 15}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                1
            
            FROM auth.users WHERE email = 'robert.jackson10@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.69137224263519,
                -117.18574577717746,
                'San Diego',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'south',
                '{"direction": "long_haul", "truck_type": "Refrigerated", "available_hours": 4}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                48,
                5
            
            FROM auth.users WHERE email = 'emma.johnson85@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.70004921264142,
                -117.15620335739,
                'San Diego',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Van", "available_hours": 62}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                74,
                0
            
            FROM auth.users WHERE email = 'john.wilson37@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.70464956283042,
                -117.20520224679323,
                'San Diego',
                'United States',
                'Denver',
                'United States',
                39.7392,
                -104.9903,
                'south',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 66}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                37,
                4
            
            FROM auth.users WHERE email = 'lisa.brown63@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.71234701587205,
                -117.13424686719766,
                'San Diego',
                'United States',
                'Las Vegas',
                'United States',
                36.1699,
                -115.1398,
                'long_haul',
                '{"direction": "south", "truck_type": "Box Truck", "available_hours": 11}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                15,
                2
            
            FROM auth.users WHERE email = 'jessica.anderson22@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.74988316385538,
                -117.17560232991187,
                'San Diego',
                'United States',
                'Sacramento',
                'United States',
                38.5816,
                -121.4944,
                'south',
                '{"direction": "local", "truck_type": "Box Truck", "available_hours": 36}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                1
            
            FROM auth.users WHERE email = 'emma.moore80@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.67064090684991,
                -117.13578261589306,
                'San Diego',
                'United States',
                'Milwaukee',
                'United States',
                43.0389,
                -87.9065,
                'long_haul',
                '{"direction": "west", "truck_type": "20T", "available_hours": 40}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                1
            
            FROM auth.users WHERE email = 'david.thomas74@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.73450146200232,
                -117.20139147228925,
                'San Diego',
                'United States',
                'Baltimore',
                'United States',
                39.2904,
                -76.6122,
                'south',
                '{"direction": "east", "truck_type": "Refrigerated", "available_hours": 3}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                62,
                1
            
            FROM auth.users WHERE email = 'emma.johnson27@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.72033624551289,
                -117.11404858121618,
                'San Diego',
                'United States',
                'Long Beach',
                'United States',
                33.7701,
                -118.1937,
                'long_haul',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 63}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                81,
                5
            
            FROM auth.users WHERE email = 'sarah.brown12@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.6945898941477,
                -117.16009621319871,
                'San Diego',
                'United States',
                'Atlanta',
                'United States',
                33.749,
                -84.388,
                'local',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 17}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                58,
                3
            
            FROM auth.users WHERE email = 'sarah.smith63@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.57698820108852,
                -117.00017231457885,
                'Otay Mesa',
                'United States',
                'New York',
                'United States',
                40.7128,
                -74.006,
                'long_haul',
                '{"direction": "long_haul", "truck_type": "Flatbed", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                90,
                5
            
            FROM auth.users WHERE email = 'john.moore55@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.53331563637882,
                -116.97015306596666,
                'Otay Mesa',
                'United States',
                'Dallas',
                'United States',
                32.7767,
                -96.797,
                'north',
                '{"direction": "long_haul", "truck_type": "20T", "available_hours": 37}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                1
            
            FROM auth.users WHERE email = 'lisa.brown45@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.530041481528,
                -116.98590418836174,
                'Otay Mesa',
                'United States',
                'Salt Lake City',
                'United States',
                40.7608,
                -111.891,
                'local',
                '{"direction": "north", "truck_type": "Refrigerated", "available_hours": 50}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                73,
                3
            
            FROM auth.users WHERE email = 'david.brown85@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.52498807926299,
                -117.01498256571224,
                'Otay Mesa',
                'United States',
                'Tucson',
                'United States',
                32.2226,
                -110.9747,
                'north',
                '{"direction": "west", "truck_type": "Van", "available_hours": 21}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                91,
                3
            
            FROM auth.users WHERE email = 'david.jackson44@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.58195886393861,
                -116.95078058110774,
                'Otay Mesa',
                'United States',
                'Detroit',
                'United States',
                42.3314,
                -83.0458,
                'north',
                '{"direction": "south", "truck_type": "Flatbed", "available_hours": 27}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                85,
                3
            
            FROM auth.users WHERE email = 'lisa.anderson42@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.52948251087289,
                -116.98631334936496,
                'Otay Mesa',
                'United States',
                'Portland',
                'United States',
                45.5152,
                -122.6784,
                'north',
                '{"direction": "north", "truck_type": "Box Truck", "available_hours": 19}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                59,
                1
            
            FROM auth.users WHERE email = 'sarah.taylor85@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                32.61314965705646,
                -117.00249447705578,
                'Otay Mesa',
                'United States',
                'San Diego',
                'United States',
                32.7157,
                -117.1611,
                'north',
                '{"direction": "west", "truck_type": "Van", "available_hours": 26}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                17,
                3
            
            FROM auth.users WHERE email = 'tom.doe71@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                37.74363511505042,
                -122.45480190486089,
                'San Francisco',
                'United States',
                'Oklahoma City',
                'United States',
                35.4676,
                -97.5164,
                'north',
                '{"direction": "long_haul", "truck_type": "Box Truck", "available_hours": 31}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                64,
                0
            
            FROM auth.users WHERE email = 'robert.moore15@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                37.751181110003444,
                -122.46316194723575,
                'San Francisco',
                'United States',
                'San Jose',
                'United States',
                37.3382,
                -121.8863,
                'south',
                '{"direction": "east", "truck_type": "Box Truck", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                9,
                4
            
            FROM auth.users WHERE email = 'robert.taylor99@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                37.76895964273526,
                -122.38323480204906,
                'San Francisco',
                'United States',
                'Indianapolis',
                'United States',
                39.7684,
                -86.1581,
                'north',
                '{"direction": "east", "truck_type": "Van", "available_hours": 13}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                97,
                5
            
            FROM auth.users WHERE email = 'lisa.jackson15@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                37.738432356316224,
                -122.45587517167195,
                'San Francisco',
                'United States',
                'Dallas',
                'United States',
                32.7767,
                -96.797,
                'north',
                '{"direction": "north", "truck_type": "20T", "available_hours": 59}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                52,
                0
            
            FROM auth.users WHERE email = 'tom.brown82@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                37.74680740990971,
                -122.43219554002447,
                'San Francisco',
                'United States',
                'Chicago',
                'United States',
                41.8781,
                -87.6298,
                'local',
                '{"direction": "local", "truck_type": "Van", "available_hours": 70}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                21,
                3
            
            FROM auth.users WHERE email = 'tom.wilson72@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                37.769573221863695,
                -122.46178755842595,
                'San Francisco',
                'United States',
                'Philadelphia',
                'United States',
                39.9526,
                -75.1652,
                'local',
                '{"direction": "south", "truck_type": "Van", "available_hours": 2}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                20,
                2
            
            FROM auth.users WHERE email = 'john.doe68@example.com';
INSERT INTO public.community_posts (
                id,
                user_id,
                post_type,
                status,
                origin_lat,
                origin_lng,
                origin_city,
                origin_country,
                dest_city,
                dest_country,
                dest_lat,
                dest_lng,
                template_key,
                metadata,
                contact_phone,
                contact_whatsapp,
                created_at,
                updated_at,
                expires_at,
                view_count,
                contact_count
            )  SELECT
                gen_random_uuid(),
                auth.users.id,
                
                'DRIVER_AVAILABLE',
                'active',
                37.82245746442142,
                -122.42831726599687,
                'San Francisco',
                'United States',
                'Austin',
                'United States',
                30.2672,
                -97.7431,
                'long_haul',
                '{"direction": "south", "truck_type": "Refrigerated", "available_hours": 44}',
                '',
                FALSE,
                '2026-01-22T09:32:00.500819',
                '2026-01-22T09:32:00.500819',
                '2026-01-23T09:32:00.500819',
                28,
                0
            
            FROM auth.users WHERE email = 'robert.doe99@example.com';
